// Code generated by protoc-gen-go. DO NOT EDIT.
// source: address.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Address describes general address
type Address struct {
	// Types that are valid to be assigned to DomainOptional:
	//	*Address_AddressDomain
	DomainOptional isAddress_DomainOptional `protobuf_oneof:"domain_optional"`
	// Types that are valid to be assigned to AddressOptional:
	//	*Address_S3
	//	*Address_Kafka
	//	*Address_Digest
	//	*Address_Uuid
	//	*Address_UserId
	//	*Address_Dirname
	//	*Address_Filename
	//	*Address_Url
	//	*Address_Domain
	//	*Address_CustomString
	AddressOptional      isAddress_AddressOptional `protobuf_oneof:"address_optional"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Address) Reset()      { *m = Address{} }
func (*Address) ProtoMessage() {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

type isAddress_DomainOptional interface {
	isAddress_DomainOptional()
}

type Address_AddressDomain struct {
	AddressDomain *Domain `protobuf:"bytes,10,opt,name=address_domain,json=addressDomain,proto3,oneof"`
}

func (*Address_AddressDomain) isAddress_DomainOptional() {}

func (m *Address) GetDomainOptional() isAddress_DomainOptional {
	if m != nil {
		return m.DomainOptional
	}
	return nil
}

func (m *Address) GetAddressDomain() *Domain {
	if x, ok := m.GetDomainOptional().(*Address_AddressDomain); ok {
		return x.AddressDomain
	}
	return nil
}

type isAddress_AddressOptional interface {
	isAddress_AddressOptional()
}

type Address_S3 struct {
	S3 *S3Address `protobuf:"bytes,100,opt,name=s3,proto3,oneof"`
}

type Address_Kafka struct {
	Kafka *KafkaAddress `protobuf:"bytes,200,opt,name=kafka,proto3,oneof"`
}

type Address_Digest struct {
	Digest *Digest `protobuf:"bytes,300,opt,name=digest,proto3,oneof"`
}

type Address_Uuid struct {
	Uuid *UUID `protobuf:"bytes,400,opt,name=uuid,proto3,oneof"`
}

type Address_UserId struct {
	UserId *UserID `protobuf:"bytes,500,opt,name=user_id,json=userId,proto3,oneof"`
}

type Address_Dirname struct {
	Dirname *Dirname `protobuf:"bytes,600,opt,name=dirname,proto3,oneof"`
}

type Address_Filename struct {
	Filename *Filename `protobuf:"bytes,700,opt,name=filename,proto3,oneof"`
}

type Address_Url struct {
	Url *URL `protobuf:"bytes,800,opt,name=url,proto3,oneof"`
}

type Address_Domain struct {
	Domain *Domain `protobuf:"bytes,900,opt,name=domain,proto3,oneof"`
}

type Address_CustomString struct {
	CustomString string `protobuf:"bytes,1000,opt,name=custom_string,json=customString,proto3,oneof"`
}

func (*Address_S3) isAddress_AddressOptional() {}

func (*Address_Kafka) isAddress_AddressOptional() {}

func (*Address_Digest) isAddress_AddressOptional() {}

func (*Address_Uuid) isAddress_AddressOptional() {}

func (*Address_UserId) isAddress_AddressOptional() {}

func (*Address_Dirname) isAddress_AddressOptional() {}

func (*Address_Filename) isAddress_AddressOptional() {}

func (*Address_Url) isAddress_AddressOptional() {}

func (*Address_Domain) isAddress_AddressOptional() {}

func (*Address_CustomString) isAddress_AddressOptional() {}

func (m *Address) GetAddressOptional() isAddress_AddressOptional {
	if m != nil {
		return m.AddressOptional
	}
	return nil
}

func (m *Address) GetS3() *S3Address {
	if x, ok := m.GetAddressOptional().(*Address_S3); ok {
		return x.S3
	}
	return nil
}

func (m *Address) GetKafka() *KafkaAddress {
	if x, ok := m.GetAddressOptional().(*Address_Kafka); ok {
		return x.Kafka
	}
	return nil
}

func (m *Address) GetDigest() *Digest {
	if x, ok := m.GetAddressOptional().(*Address_Digest); ok {
		return x.Digest
	}
	return nil
}

func (m *Address) GetUUID() *UUID {
	if x, ok := m.GetAddressOptional().(*Address_Uuid); ok {
		return x.Uuid
	}
	return nil
}

func (m *Address) GetUserId() *UserID {
	if x, ok := m.GetAddressOptional().(*Address_UserId); ok {
		return x.UserId
	}
	return nil
}

func (m *Address) GetDirname() *Dirname {
	if x, ok := m.GetAddressOptional().(*Address_Dirname); ok {
		return x.Dirname
	}
	return nil
}

func (m *Address) GetFilename() *Filename {
	if x, ok := m.GetAddressOptional().(*Address_Filename); ok {
		return x.Filename
	}
	return nil
}

func (m *Address) GetUrl() *URL {
	if x, ok := m.GetAddressOptional().(*Address_Url); ok {
		return x.Url
	}
	return nil
}

func (m *Address) GetDomain() *Domain {
	if x, ok := m.GetAddressOptional().(*Address_Domain); ok {
		return x.Domain
	}
	return nil
}

func (m *Address) GetCustomString() string {
	if x, ok := m.GetAddressOptional().(*Address_CustomString); ok {
		return x.CustomString
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Address) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Address_AddressDomain)(nil),
		(*Address_S3)(nil),
		(*Address_Kafka)(nil),
		(*Address_Digest)(nil),
		(*Address_Uuid)(nil),
		(*Address_UserId)(nil),
		(*Address_Dirname)(nil),
		(*Address_Filename)(nil),
		(*Address_Url)(nil),
		(*Address_Domain)(nil),
		(*Address_CustomString)(nil),
	}
}

func init() {
	proto.RegisterType((*Address)(nil), "atlas.Address")
}

func init() { proto.RegisterFile("address.proto", fileDescriptor_982c640dad8fe78e) }

var fileDescriptor_982c640dad8fe78e = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4d, 0x8e, 0xda, 0x30,
	0x14, 0x80, 0x6b, 0x7e, 0x92, 0xf2, 0x20, 0x40, 0xcd, 0xc6, 0x62, 0xd3, 0x8a, 0x45, 0x45, 0xd5,
	0x2a, 0x8b, 0x46, 0xea, 0xbe, 0x08, 0x55, 0x46, 0xed, 0xca, 0x88, 0x75, 0xe4, 0xd6, 0x01, 0x45,
	0x84, 0x04, 0xd9, 0xc9, 0x09, 0xda, 0x03, 0xf4, 0x08, 0x3d, 0x40, 0x8f, 0xd0, 0x03, 0xf4, 0x08,
	0x73, 0x84, 0x39, 0xc0, 0x1c, 0x60, 0x94, 0x67, 0x9b, 0x19, 0x46, 0xb3, 0xc3, 0xdf, 0xfb, 0xde,
	0xe3, 0xfd, 0x04, 0x22, 0xa9, 0x94, 0xce, 0x8c, 0x89, 0xcf, 0xba, 0xaa, 0x2b, 0xda, 0x97, 0x75,
	0x21, 0xcd, 0x7c, 0xa4, 0xf2, 0x43, 0x66, 0x6a, 0x0b, 0xe7, 0x91, 0xca, 0x75, 0x29, 0x4f, 0x99,
	0x7b, 0x8e, 0x54, 0x75, 0x92, 0x79, 0xe9, 0x5e, 0xe3, 0x7d, 0x5e, 0x64, 0x8f, 0xa2, 0xb3, 0xa3,
	0xdc, 0x1f, 0x65, 0x7a, 0x55, 0x76, 0x3e, 0x35, 0xc9, 0x13, 0x32, 0x68, 0x74, 0xe1, 0xcb, 0x37,
	0x26, 0xd3, 0x69, 0xae, 0xdc, 0x13, 0x9a, 0xc6, 0xff, 0x5e, 0xfc, 0xec, 0x41, 0xf8, 0xd9, 0xe6,
	0xd1, 0x4f, 0x30, 0x76, 0x25, 0x52, 0xdb, 0x00, 0x83, 0x37, 0x64, 0x39, 0xfc, 0x18, 0xc5, 0xd8,
	0x73, 0xbc, 0x46, 0xc8, 0x5f, 0x08, 0x3f, 0x92, 0x05, 0x74, 0x01, 0x1d, 0x93, 0x30, 0x85, 0xee,
	0xd4, 0xb9, 0xdb, 0xc4, 0x55, 0xe5, 0x44, 0x74, 0x4c, 0x42, 0x3f, 0x40, 0x1f, 0xdb, 0x66, 0xff,
	0x09, 0x7a, 0x33, 0xe7, 0x7d, 0x6d, 0xe1, 0x83, 0x6a, 0x25, 0xba, 0x84, 0xc0, 0xee, 0x87, 0xfd,
	0xed, 0x5c, 0xb7, 0x80, 0x94, 0x13, 0xe1, 0xe2, 0x74, 0x01, 0xbd, 0x76, 0x1a, 0xf6, 0xbb, 0x8b,
	0xde, 0xd0, 0x79, 0xbb, 0xdd, 0x66, 0xcd, 0x89, 0xc0, 0x18, 0x7d, 0x07, 0xa1, 0x5b, 0x00, 0xbb,
	0xeb, 0x5e, 0x95, 0xdb, 0x99, 0x4c, 0xa3, 0x18, 0xb4, 0xc2, 0x46, 0xd1, 0xf7, 0x10, 0xba, 0x53,
	0xb0, 0x9b, 0x1e, 0xaa, 0xe3, 0xcb, 0x3f, 0x23, 0xe6, 0x44, 0x78, 0x83, 0xc6, 0xf0, 0xd2, 0x9f,
	0x86, 0xfd, 0xeb, 0xa3, 0x3d, 0x71, 0xf6, 0x17, 0xc7, 0x39, 0x11, 0x17, 0x87, 0xbe, 0x86, 0x6e,
	0xa3, 0x0b, 0xf6, 0x27, 0x40, 0x15, 0x7c, 0x0f, 0xe2, 0x1b, 0x27, 0xa2, 0x8d, 0xe0, 0xd8, 0x76,
	0xf1, 0xbf, 0xc2, 0xe7, 0x36, 0xdf, 0x8e, 0x6d, 0x57, 0xfe, 0x16, 0xa2, 0x1f, 0x8d, 0xa9, 0xab,
	0x53, 0x6a, 0x6a, 0x9d, 0x97, 0x07, 0x76, 0xdb, 0x26, 0x0c, 0x38, 0x11, 0x23, 0xcb, 0xb7, 0x88,
	0x57, 0xaf, 0x60, 0x62, 0x33, 0xd2, 0xea, 0x5c, 0xe7, 0x55, 0x29, 0x8b, 0x15, 0x85, 0xa9, 0xbf,
	0xb2, 0x67, 0xdf, 0x03, 0xfc, 0x18, 0x92, 0xfb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0xa3, 0x95,
	0x1d, 0xac, 0x02, 0x00, 0x00,
}
