// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Command represents a command used by Control Plane to exchange commands between server and client(s).
type Command struct {
	// Header of the command
	Header *Metadata `protobuf:"bytes,100,opt,name=header,proto3" json:"header,omitempty"`
	// Optional. Any arbitrary sequence of bytes no longer than 2^32
	Bytes []byte `protobuf:"bytes,200,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// Optional. Multiple command's subjects.
	Subjects []*Metadata `protobuf:"bytes,300,rep,name=subjects,proto3" json:"subjects,omitempty"`
	// Optional. Recursive chain of commands
	Commands             []*Command `protobuf:"bytes,400,rep,name=commands,proto3" json:"commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Command) Reset()      { *m = Command{} }
func (*Command) ProtoMessage() {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetHeader() *Metadata {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Command) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Command) GetSubjects() []*Metadata {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func (m *Command) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

func init() {
	proto.RegisterType((*Command)(nil), "atlas.Command")
}

func init() { proto.RegisterFile("command.proto", fileDescriptor_213c0bb044472049) }

var fileDescriptor_213c0bb044472049 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2c, 0xc9, 0x49, 0x2c,
	0x96, 0xe2, 0xcb, 0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c, 0x49, 0x84, 0x08, 0x2b, 0x2d, 0x61, 0xe4,
	0x62, 0x77, 0x86, 0x28, 0x14, 0x52, 0xe7, 0x62, 0xcb, 0x48, 0x4d, 0x4c, 0x49, 0x2d, 0x92, 0x48,
	0x51, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd7, 0x03, 0xeb, 0xd1, 0xf3, 0x85, 0x6a, 0x09, 0x82, 0x4a,
	0x0b, 0x89, 0x72, 0xb1, 0x26, 0x55, 0x96, 0xa4, 0x16, 0x4b, 0x9c, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x09, 0x82, 0xf0, 0x84, 0x74, 0xb8, 0x38, 0x8a, 0x4b, 0x93, 0xb2, 0x52, 0x93, 0x4b, 0x8a, 0x25,
	0xd6, 0x30, 0x29, 0x30, 0x63, 0x33, 0x02, 0xae, 0x42, 0x48, 0x9b, 0x8b, 0x03, 0xea, 0xc2, 0x62,
	0x89, 0x09, 0xcc, 0x60, 0xd5, 0x7c, 0x50, 0xd5, 0x50, 0x07, 0x05, 0xc1, 0x15, 0x24, 0xb1, 0x81,
	0x5d, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xbc, 0xf2, 0xab, 0xd5, 0x00, 0x00, 0x00,
}
