// Code generated by protoc-gen-go. DO NOT EDIT.
// source: diff_task.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// DiffTask represents request for diff between two objects.
type DiffTask struct {
	// "A" party for diff
	A *Address `protobuf:"bytes,100,opt,name=a,proto3" json:"a,omitempty"`
	// "B" party for diff
	B *Address `protobuf:"bytes,200,opt,name=b,proto3" json:"b,omitempty"`
	// TODO
	Meta                 *Address `protobuf:"bytes,300,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiffTask) Reset()      { *m = DiffTask{} }
func (*DiffTask) ProtoMessage() {}
func (*DiffTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb1af03f8bda6837, []int{0}
}

func (m *DiffTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiffTask.Unmarshal(m, b)
}
func (m *DiffTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiffTask.Marshal(b, m, deterministic)
}
func (m *DiffTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiffTask.Merge(m, src)
}
func (m *DiffTask) XXX_Size() int {
	return xxx_messageInfo_DiffTask.Size(m)
}
func (m *DiffTask) XXX_DiscardUnknown() {
	xxx_messageInfo_DiffTask.DiscardUnknown(m)
}

var xxx_messageInfo_DiffTask proto.InternalMessageInfo

func (m *DiffTask) GetA() *Address {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *DiffTask) GetB() *Address {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *DiffTask) GetMeta() *Address {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*DiffTask)(nil), "atlas.DiffTask")
}

func init() { proto.RegisterFile("diff_task.proto", fileDescriptor_bb1af03f8bda6837) }

var fileDescriptor_bb1af03f8bda6837 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xc9, 0x4c, 0x4b,
	0x8b, 0x2f, 0x49, 0x2c, 0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2c, 0xc9,
	0x49, 0x2c, 0x96, 0xe2, 0x4d, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x86, 0x88, 0x2a, 0xe5, 0x70,
	0x71, 0xb8, 0x64, 0xa6, 0xa5, 0x85, 0x24, 0x16, 0x67, 0x0b, 0xc9, 0x70, 0x31, 0x26, 0x4a, 0xa4,
	0x28, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xe9, 0x81, 0x55, 0xeb, 0x39, 0x42, 0x14, 0x07, 0x31, 0x26,
	0x0a, 0xc9, 0x72, 0x31, 0x26, 0x49, 0x9c, 0x60, 0xc4, 0x2e, 0x9d, 0x24, 0xa4, 0xcc, 0xc5, 0x92,
	0x9b, 0x5a, 0x92, 0x28, 0xb1, 0x86, 0x09, 0xab, 0x0a, 0xb0, 0x64, 0x12, 0x1b, 0xd8, 0x52, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xe6, 0x6f, 0x5d, 0x9d, 0x00, 0x00, 0x00,
}
