// source: diff_task.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var address_pb = require('./address_pb.js');
goog.object.extend(proto, address_pb);
goog.exportSymbol('proto.atlas.DiffTask', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.atlas.DiffTask = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.atlas.DiffTask, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.atlas.DiffTask.displayName = 'proto.atlas.DiffTask';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.atlas.DiffTask.prototype.toObject = function(opt_includeInstance) {
  return proto.atlas.DiffTask.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.atlas.DiffTask} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.atlas.DiffTask.toObject = function(includeInstance, msg) {
  var f, obj = {
    a: (f = msg.getA()) && address_pb.Address.toObject(includeInstance, f),
    b: (f = msg.getB()) && address_pb.Address.toObject(includeInstance, f),
    meta: (f = msg.getMeta()) && address_pb.Address.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.atlas.DiffTask}
 */
proto.atlas.DiffTask.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.atlas.DiffTask;
  return proto.atlas.DiffTask.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.atlas.DiffTask} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.atlas.DiffTask}
 */
proto.atlas.DiffTask.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 100:
      var value = new address_pb.Address;
      reader.readMessage(value,address_pb.Address.deserializeBinaryFromReader);
      msg.setA(value);
      break;
    case 200:
      var value = new address_pb.Address;
      reader.readMessage(value,address_pb.Address.deserializeBinaryFromReader);
      msg.setB(value);
      break;
    case 300:
      var value = new address_pb.Address;
      reader.readMessage(value,address_pb.Address.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.atlas.DiffTask.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.atlas.DiffTask.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.atlas.DiffTask} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.atlas.DiffTask.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getA();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      address_pb.Address.serializeBinaryToWriter
    );
  }
  f = message.getB();
  if (f != null) {
    writer.writeMessage(
      200,
      f,
      address_pb.Address.serializeBinaryToWriter
    );
  }
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      300,
      f,
      address_pb.Address.serializeBinaryToWriter
    );
  }
};


/**
 * optional Address a = 100;
 * @return {?proto.atlas.Address}
 */
proto.atlas.DiffTask.prototype.getA = function() {
  return /** @type{?proto.atlas.Address} */ (
    jspb.Message.getWrapperField(this, address_pb.Address, 100));
};


/**
 * @param {?proto.atlas.Address|undefined} value
 * @return {!proto.atlas.DiffTask} returns this
*/
proto.atlas.DiffTask.prototype.setA = function(value) {
  return jspb.Message.setWrapperField(this, 100, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.atlas.DiffTask} returns this
 */
proto.atlas.DiffTask.prototype.clearA = function() {
  return this.setA(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.atlas.DiffTask.prototype.hasA = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * optional Address b = 200;
 * @return {?proto.atlas.Address}
 */
proto.atlas.DiffTask.prototype.getB = function() {
  return /** @type{?proto.atlas.Address} */ (
    jspb.Message.getWrapperField(this, address_pb.Address, 200));
};


/**
 * @param {?proto.atlas.Address|undefined} value
 * @return {!proto.atlas.DiffTask} returns this
*/
proto.atlas.DiffTask.prototype.setB = function(value) {
  return jspb.Message.setWrapperField(this, 200, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.atlas.DiffTask} returns this
 */
proto.atlas.DiffTask.prototype.clearB = function() {
  return this.setB(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.atlas.DiffTask.prototype.hasB = function() {
  return jspb.Message.getField(this, 200) != null;
};


/**
 * optional Address meta = 300;
 * @return {?proto.atlas.Address}
 */
proto.atlas.DiffTask.prototype.getMeta = function() {
  return /** @type{?proto.atlas.Address} */ (
    jspb.Message.getWrapperField(this, address_pb.Address, 300));
};


/**
 * @param {?proto.atlas.Address|undefined} value
 * @return {!proto.atlas.DiffTask} returns this
*/
proto.atlas.DiffTask.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 300, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.atlas.DiffTask} returns this
 */
proto.atlas.DiffTask.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.atlas.DiffTask.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 300) != null;
};


goog.object.extend(exports, proto.atlas);
