// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objects_list.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ObjectsList struct {
	Status               *Status   `protobuf:"bytes,100,opt,name=status,proto3" json:"status,omitempty"`
	Reports              []*Report `protobuf:"bytes,500,rep,name=reports,proto3" json:"reports,omitempty"`
	Tasks                []*Task   `protobuf:"bytes,600,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Statuses             []*Status `protobuf:"bytes,700,rep,name=statuses,proto3" json:"statuses,omitempty"`
	Files                []*File   `protobuf:"bytes,800,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ObjectsList) Reset()      { *m = ObjectsList{} }
func (*ObjectsList) ProtoMessage() {}
func (*ObjectsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_63c21e46b44ccad6, []int{0}
}

func (m *ObjectsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectsList.Unmarshal(m, b)
}
func (m *ObjectsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectsList.Marshal(b, m, deterministic)
}
func (m *ObjectsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectsList.Merge(m, src)
}
func (m *ObjectsList) XXX_Size() int {
	return xxx_messageInfo_ObjectsList.Size(m)
}
func (m *ObjectsList) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectsList.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectsList proto.InternalMessageInfo

func (m *ObjectsList) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ObjectsList) GetReports() []*Report {
	if m != nil {
		return m.Reports
	}
	return nil
}

func (m *ObjectsList) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *ObjectsList) GetStatuses() []*Status {
	if m != nil {
		return m.Statuses
	}
	return nil
}

func (m *ObjectsList) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterType((*ObjectsList)(nil), "atlas.ObjectsList")
}

func init() { proto.RegisterFile("objects_list.proto", fileDescriptor_63c21e46b44ccad6) }

var fileDescriptor_63c21e46b44ccad6 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0x4f, 0xca, 0x4a,
	0x4d, 0x2e, 0x29, 0x8e, 0xcf, 0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x4d, 0x2c, 0xc9, 0x49, 0x2c, 0x96, 0xe2, 0x4a, 0xcb, 0xcc, 0x49, 0x85, 0x08, 0x49, 0xf1, 0x14,
	0xa5, 0x16, 0xe4, 0x17, 0x41, 0x15, 0x48, 0x71, 0x95, 0x24, 0x16, 0x67, 0xc3, 0x64, 0x8a, 0x4b,
	0x12, 0x4b, 0x4a, 0x8b, 0x21, 0x3c, 0xa5, 0x4b, 0x8c, 0x5c, 0xdc, 0xfe, 0x10, 0x13, 0x7d, 0x32,
	0x8b, 0x4b, 0x84, 0x54, 0xb9, 0xd8, 0x20, 0xf2, 0x12, 0x29, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xbc,
	0x7a, 0x60, 0xb3, 0xf5, 0x82, 0xc1, 0x82, 0x41, 0x50, 0x49, 0x21, 0x0d, 0x2e, 0x76, 0x88, 0x05,
	0xc5, 0x12, 0x5f, 0x98, 0x15, 0x98, 0x91, 0x14, 0x06, 0x81, 0x85, 0x83, 0x60, 0xd2, 0x42, 0x4a,
	0x5c, 0xac, 0x20, 0xcb, 0x8b, 0x25, 0x6e, 0xb0, 0x80, 0xd5, 0x71, 0x43, 0xd5, 0x85, 0x24, 0x16,
	0x67, 0x07, 0x41, 0xa4, 0x84, 0xb4, 0xb8, 0x38, 0x20, 0xe6, 0xa6, 0x16, 0x4b, 0xec, 0x61, 0x45,
	0x31, 0x0e, 0x6a, 0x2f, 0x5c, 0x1e, 0x64, 0x1e, 0xc8, 0x9b, 0xc5, 0x12, 0x0b, 0xd8, 0x50, 0xcc,
	0x73, 0xcb, 0xcc, 0x49, 0x0d, 0x82, 0x48, 0x25, 0xb1, 0x81, 0xfd, 0x66, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x29, 0xbb, 0xa6, 0x0b, 0x2c, 0x01, 0x00, 0x00,
}
