// Code generated by protoc-gen-go. DO NOT EDIT.
// source: object_request.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ObjectRequest represents request for the object(s)
type ObjectRequest struct {
	Header               *Metadata `protobuf:"bytes,100,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ObjectRequest) Reset()      { *m = ObjectRequest{} }
func (*ObjectRequest) ProtoMessage() {}
func (*ObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_075bd3731b60164f, []int{0}
}

func (m *ObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectRequest.Unmarshal(m, b)
}
func (m *ObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectRequest.Marshal(b, m, deterministic)
}
func (m *ObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectRequest.Merge(m, src)
}
func (m *ObjectRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectRequest.Size(m)
}
func (m *ObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectRequest proto.InternalMessageInfo

func (m *ObjectRequest) GetHeader() *Metadata {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*ObjectRequest)(nil), "atlas.ObjectRequest")
}

func init() { proto.RegisterFile("object_request.proto", fileDescriptor_075bd3731b60164f) }

var fileDescriptor_075bd3731b60164f = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0x4f, 0xca, 0x4a,
	0x4d, 0x2e, 0x89, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x4d, 0x2c, 0xc9, 0x49, 0x2c, 0x96, 0xe2, 0xcb, 0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c,
	0x49, 0x84, 0x08, 0x2b, 0x59, 0x70, 0xf1, 0xfa, 0x83, 0x95, 0x07, 0x41, 0x54, 0x0b, 0xa9, 0x73,
	0xb1, 0x65, 0xa4, 0x26, 0xa6, 0xa4, 0x16, 0x49, 0xa4, 0x28, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xeb,
	0x81, 0x35, 0xea, 0xf9, 0x42, 0xf5, 0x05, 0x41, 0xa5, 0x93, 0xd8, 0xc0, 0x06, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x68, 0xf8, 0x3f, 0x69, 0x6f, 0x00, 0x00, 0x00,
}
