// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objects_request.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ObjectsRequest struct {
	// Types that are valid to be assigned to HeaderOptional:
	//	*ObjectsRequest_Header
	HeaderOptional       isObjectsRequest_HeaderOptional `protobuf_oneof:"header_optional"`
	Requests             []*ObjectRequest                `protobuf:"bytes,300,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ObjectsRequest) Reset()      { *m = ObjectsRequest{} }
func (*ObjectsRequest) ProtoMessage() {}
func (*ObjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5aa47e742b67e756, []int{0}
}

func (m *ObjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectsRequest.Unmarshal(m, b)
}
func (m *ObjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectsRequest.Marshal(b, m, deterministic)
}
func (m *ObjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectsRequest.Merge(m, src)
}
func (m *ObjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectsRequest.Size(m)
}
func (m *ObjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectsRequest proto.InternalMessageInfo

type isObjectsRequest_HeaderOptional interface {
	isObjectsRequest_HeaderOptional()
}

type ObjectsRequest_Header struct {
	Header *Metadata `protobuf:"bytes,100,opt,name=header,proto3,oneof"`
}

func (*ObjectsRequest_Header) isObjectsRequest_HeaderOptional() {}

func (m *ObjectsRequest) GetHeaderOptional() isObjectsRequest_HeaderOptional {
	if m != nil {
		return m.HeaderOptional
	}
	return nil
}

func (m *ObjectsRequest) GetHeader() *Metadata {
	if x, ok := m.GetHeaderOptional().(*ObjectsRequest_Header); ok {
		return x.Header
	}
	return nil
}

func (m *ObjectsRequest) GetRequests() []*ObjectRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ObjectsRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ObjectsRequest_Header)(nil),
	}
}

func init() {
	proto.RegisterType((*ObjectsRequest)(nil), "atlas.ObjectsRequest")
}

func init() { proto.RegisterFile("objects_request.proto", fileDescriptor_5aa47e742b67e756) }

var fileDescriptor_5aa47e742b67e756 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x4f, 0xca, 0x4a,
	0x4d, 0x2e, 0x29, 0x8e, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x4d, 0x2c, 0xc9, 0x49, 0x2c, 0x96, 0xe2, 0xcb, 0x4d, 0x2d, 0x49, 0x4c, 0x49,
	0x2c, 0x49, 0x84, 0x08, 0x4b, 0x89, 0x40, 0x54, 0xa3, 0x2a, 0x56, 0x6a, 0x64, 0xe4, 0xe2, 0xf3,
	0x87, 0x18, 0x13, 0x04, 0x91, 0x10, 0xd2, 0xe4, 0x62, 0xcb, 0x48, 0x4d, 0x4c, 0x49, 0x2d, 0x92,
	0x48, 0x51, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd7, 0x03, 0x1b, 0xa8, 0xe7, 0x0b, 0x35, 0xcf, 0x83,
	0x21, 0x08, 0xaa, 0x40, 0xc8, 0x90, 0x8b, 0x03, 0x6a, 0x5c, 0xb1, 0xc4, 0x1a, 0x26, 0x05, 0x66,
	0x0d, 0x6e, 0x23, 0x11, 0xa8, 0x6a, 0x88, 0xa1, 0x50, 0x33, 0x83, 0xe0, 0xca, 0x9c, 0x04, 0xb9,
	0xf8, 0x21, 0x9a, 0xe3, 0xf3, 0x0b, 0x4a, 0x32, 0xf3, 0xf3, 0x12, 0x73, 0x92, 0xd8, 0xc0, 0x4e,
	0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x00, 0x96, 0x72, 0xe6, 0xd0, 0x00, 0x00, 0x00,
}
