// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objects_request.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ObjectsRequest struct {
	// Types that are valid to be assigned to DomainOptional:
	//	*ObjectsRequest_Domain
	DomainOptional isObjectsRequest_DomainOptional `protobuf_oneof:"domain_optional"`
	// Types that are valid to be assigned to RequestModeOptional:
	//	*ObjectsRequest_RequestMode
	RequestModeOptional  isObjectsRequest_RequestModeOptional `protobuf_oneof:"request_mode_optional"`
	Requests             []*ObjectRequest                     `protobuf:"bytes,300,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ObjectsRequest) Reset()      { *m = ObjectsRequest{} }
func (*ObjectsRequest) ProtoMessage() {}
func (*ObjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5aa47e742b67e756, []int{0}
}

func (m *ObjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectsRequest.Unmarshal(m, b)
}
func (m *ObjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectsRequest.Marshal(b, m, deterministic)
}
func (m *ObjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectsRequest.Merge(m, src)
}
func (m *ObjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ObjectsRequest.Size(m)
}
func (m *ObjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectsRequest proto.InternalMessageInfo

type isObjectsRequest_DomainOptional interface {
	isObjectsRequest_DomainOptional()
}

type ObjectsRequest_Domain struct {
	Domain *Domain `protobuf:"bytes,100,opt,name=domain,proto3,oneof"`
}

func (*ObjectsRequest_Domain) isObjectsRequest_DomainOptional() {}

func (m *ObjectsRequest) GetDomainOptional() isObjectsRequest_DomainOptional {
	if m != nil {
		return m.DomainOptional
	}
	return nil
}

func (m *ObjectsRequest) GetDomain() *Domain {
	if x, ok := m.GetDomainOptional().(*ObjectsRequest_Domain); ok {
		return x.Domain
	}
	return nil
}

type isObjectsRequest_RequestModeOptional interface {
	isObjectsRequest_RequestModeOptional()
}

type ObjectsRequest_RequestMode struct {
	RequestMode RequestMode `protobuf:"varint,200,opt,name=request_mode,json=requestMode,proto3,enum=atlas.RequestMode,oneof"`
}

func (*ObjectsRequest_RequestMode) isObjectsRequest_RequestModeOptional() {}

func (m *ObjectsRequest) GetRequestModeOptional() isObjectsRequest_RequestModeOptional {
	if m != nil {
		return m.RequestModeOptional
	}
	return nil
}

func (m *ObjectsRequest) GetRequestMode() RequestMode {
	if x, ok := m.GetRequestModeOptional().(*ObjectsRequest_RequestMode); ok {
		return x.RequestMode
	}
	return RequestMode_RESERVED
}

func (m *ObjectsRequest) GetRequests() []*ObjectRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ObjectsRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ObjectsRequest_Domain)(nil),
		(*ObjectsRequest_RequestMode)(nil),
	}
}

func init() {
	proto.RegisterType((*ObjectsRequest)(nil), "atlas.ObjectsRequest")
}

func init() { proto.RegisterFile("objects_request.proto", fileDescriptor_5aa47e742b67e756) }

var fileDescriptor_5aa47e742b67e756 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x4f, 0xca, 0x4a,
	0x4d, 0x2e, 0x29, 0x8e, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x4d, 0x2c, 0xc9, 0x49, 0x2c, 0x96, 0xe2, 0x49, 0xc9, 0xcf, 0x4d, 0xcc, 0xcc,
	0x83, 0x08, 0x4a, 0x09, 0x41, 0xd5, 0xc4, 0xe7, 0xe6, 0xa7, 0xa4, 0x42, 0xc5, 0x44, 0x20, 0xfa,
	0x51, 0xb5, 0x2b, 0x5d, 0x62, 0xe4, 0xe2, 0xf3, 0x87, 0x18, 0x1c, 0x04, 0x91, 0x10, 0x52, 0xe7,
	0x62, 0x83, 0x18, 0x26, 0x91, 0xa2, 0xc0, 0xa8, 0xc1, 0x6d, 0xc4, 0xab, 0x07, 0xb6, 0x42, 0xcf,
	0x05, 0x2c, 0xe8, 0xc1, 0x10, 0x04, 0x95, 0x16, 0xb2, 0xe0, 0xe2, 0x41, 0xb6, 0x47, 0xe2, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0x10, 0x54, 0x3d, 0xd4, 0x3c, 0xdf, 0xfc, 0x94, 0x54, 0x0f,
	0xc6, 0x20, 0xee, 0x22, 0x04, 0x57, 0xc8, 0x90, 0x8b, 0x03, 0xca, 0x2d, 0x96, 0x58, 0xc3, 0xa4,
	0xc0, 0xac, 0xc1, 0x6d, 0x24, 0x02, 0xd5, 0x05, 0x71, 0x0c, 0x54, 0x6f, 0x10, 0x5c, 0x99, 0x93,
	0x20, 0x17, 0x3f, 0xc4, 0xda, 0xf8, 0xfc, 0x82, 0x92, 0xcc, 0xfc, 0xbc, 0xc4, 0x1c, 0x27, 0x71,
	0x2e, 0x51, 0x64, 0xfb, 0xe1, 0x12, 0x49, 0x6c, 0x60, 0xbf, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x3e, 0xbd, 0x35, 0xd6, 0x33, 0x01, 0x00, 0x00,
}
