// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objects_list.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ObjectsList struct {
	// Types that are valid to be assigned to HeaderOptional:
	//	*ObjectsList_Header
	HeaderOptional       isObjectsList_HeaderOptional `protobuf_oneof:"header_optional"`
	Reports              []*Report                    `protobuf:"bytes,500,rep,name=reports,proto3" json:"reports,omitempty"`
	Tasks                []*Task                      `protobuf:"bytes,600,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Statuses             []*Status                    `protobuf:"bytes,700,rep,name=statuses,proto3" json:"statuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ObjectsList) Reset()      { *m = ObjectsList{} }
func (*ObjectsList) ProtoMessage() {}
func (*ObjectsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_63c21e46b44ccad6, []int{0}
}

func (m *ObjectsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectsList.Unmarshal(m, b)
}
func (m *ObjectsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectsList.Marshal(b, m, deterministic)
}
func (m *ObjectsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectsList.Merge(m, src)
}
func (m *ObjectsList) XXX_Size() int {
	return xxx_messageInfo_ObjectsList.Size(m)
}
func (m *ObjectsList) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectsList.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectsList proto.InternalMessageInfo

type isObjectsList_HeaderOptional interface {
	isObjectsList_HeaderOptional()
}

type ObjectsList_Header struct {
	Header *Metadata `protobuf:"bytes,100,opt,name=header,proto3,oneof"`
}

func (*ObjectsList_Header) isObjectsList_HeaderOptional() {}

func (m *ObjectsList) GetHeaderOptional() isObjectsList_HeaderOptional {
	if m != nil {
		return m.HeaderOptional
	}
	return nil
}

func (m *ObjectsList) GetHeader() *Metadata {
	if x, ok := m.GetHeaderOptional().(*ObjectsList_Header); ok {
		return x.Header
	}
	return nil
}

func (m *ObjectsList) GetReports() []*Report {
	if m != nil {
		return m.Reports
	}
	return nil
}

func (m *ObjectsList) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *ObjectsList) GetStatuses() []*Status {
	if m != nil {
		return m.Statuses
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ObjectsList) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ObjectsList_Header)(nil),
	}
}

func init() {
	proto.RegisterType((*ObjectsList)(nil), "atlas.ObjectsList")
}

func init() { proto.RegisterFile("objects_list.proto", fileDescriptor_63c21e46b44ccad6) }

var fileDescriptor_63c21e46b44ccad6 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xb1, 0x4e, 0x85, 0x30,
	0x14, 0x86, 0x25, 0x08, 0x9a, 0x53, 0x95, 0xd8, 0xa9, 0x61, 0x22, 0x4c, 0xe8, 0xc0, 0x80, 0x6f,
	0xe0, 0xe4, 0xa0, 0x31, 0xa9, 0xee, 0xe4, 0x20, 0x4d, 0x44, 0xd0, 0x92, 0x9e, 0xe3, 0xdb, 0xb9,
	0xfa, 0x0e, 0x3e, 0x88, 0x0f, 0x70, 0x73, 0xdb, 0x72, 0x93, 0x3b, 0xf6, 0xff, 0xbf, 0x7c, 0xfd,
	0x0f, 0x48, 0x3b, 0x7c, 0x98, 0x37, 0xa6, 0x7e, 0x99, 0x88, 0xdb, 0xd5, 0x59, 0xb6, 0x32, 0x43,
	0x5e, 0x90, 0xca, 0xab, 0x4f, 0xc3, 0x38, 0x22, 0x63, 0x88, 0xcb, 0x0b, 0x67, 0x56, 0xeb, 0x22,
	0x54, 0x02, 0x23, 0xcd, 0x5b, 0x43, 0x8c, 0xfc, 0x4d, 0xe1, 0x55, 0xff, 0x26, 0x20, 0x9e, 0x83,
	0xf5, 0x71, 0x22, 0x96, 0x37, 0x90, 0xbf, 0x1b, 0x1c, 0x8d, 0x53, 0x63, 0x95, 0x34, 0xa2, 0x2b,
	0x5a, 0xef, 0x6f, 0x9f, 0xa2, 0xfe, 0xe1, 0x44, 0x47, 0x40, 0x36, 0x70, 0x16, 0x3e, 0x21, 0xf5,
	0x9f, 0x56, 0x69, 0x23, 0xba, 0xcb, 0x08, 0x6b, 0x1f, 0xeb, 0xad, 0x96, 0x35, 0x64, 0xfb, 0x01,
	0xa4, 0xfe, 0x4e, 0x3d, 0x27, 0x22, 0xf7, 0x8a, 0x34, 0xeb, 0x50, 0xc9, 0x5b, 0x38, 0x0f, 0xc3,
	0x0c, 0xa9, 0x9f, 0xec, 0x48, 0xf7, 0xe2, 0x73, 0x7d, 0xe8, 0xef, 0xaf, 0xa1, 0x08, 0x1b, 0x7a,
	0xbb, 0xf2, 0x64, 0xbf, 0x70, 0x19, 0x72, 0x7f, 0xce, 0xdd, 0x2e, 0x00, 0x00, 0xff, 0xff, 0xf0,
	0x03, 0xe6, 0x76, 0x23, 0x01, 0x00, 0x00,
}
