// Code generated by protoc-gen-go. DO NOT EDIT.
// source: presentation_options.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// PresentationOptions describes presentation options of the object
type PresentationOptions struct {
	// Types that are valid to be assigned to EncodingOptional:
	//	*PresentationOptions_Encoding
	EncodingOptional isPresentationOptions_EncodingOptional `protobuf_oneof:"encoding_optional"`
	// Types that are valid to be assigned to CompressionOptional:
	//	*PresentationOptions_Compression
	CompressionOptional isPresentationOptions_CompressionOptional `protobuf_oneof:"compression_optional"`
	// Types that are valid to be assigned to DigestOptional:
	//	*PresentationOptions_Digest
	DigestOptional       isPresentationOptions_DigestOptional `protobuf_oneof:"digest_optional"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *PresentationOptions) Reset()      { *m = PresentationOptions{} }
func (*PresentationOptions) ProtoMessage() {}
func (*PresentationOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96e64fc87a45d1f, []int{0}
}

func (m *PresentationOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresentationOptions.Unmarshal(m, b)
}
func (m *PresentationOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresentationOptions.Marshal(b, m, deterministic)
}
func (m *PresentationOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresentationOptions.Merge(m, src)
}
func (m *PresentationOptions) XXX_Size() int {
	return xxx_messageInfo_PresentationOptions.Size(m)
}
func (m *PresentationOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_PresentationOptions.DiscardUnknown(m)
}

var xxx_messageInfo_PresentationOptions proto.InternalMessageInfo

type isPresentationOptions_EncodingOptional interface {
	isPresentationOptions_EncodingOptional()
}

type PresentationOptions_Encoding struct {
	Encoding *Encoding `protobuf:"bytes,800,opt,name=encoding,proto3,oneof"`
}

func (*PresentationOptions_Encoding) isPresentationOptions_EncodingOptional() {}

func (m *PresentationOptions) GetEncodingOptional() isPresentationOptions_EncodingOptional {
	if m != nil {
		return m.EncodingOptional
	}
	return nil
}

func (m *PresentationOptions) GetEncoding() *Encoding {
	if x, ok := m.GetEncodingOptional().(*PresentationOptions_Encoding); ok {
		return x.Encoding
	}
	return nil
}

type isPresentationOptions_CompressionOptional interface {
	isPresentationOptions_CompressionOptional()
}

type PresentationOptions_Compression struct {
	Compression *Compression `protobuf:"bytes,900,opt,name=compression,proto3,oneof"`
}

func (*PresentationOptions_Compression) isPresentationOptions_CompressionOptional() {}

func (m *PresentationOptions) GetCompressionOptional() isPresentationOptions_CompressionOptional {
	if m != nil {
		return m.CompressionOptional
	}
	return nil
}

func (m *PresentationOptions) GetCompression() *Compression {
	if x, ok := m.GetCompressionOptional().(*PresentationOptions_Compression); ok {
		return x.Compression
	}
	return nil
}

type isPresentationOptions_DigestOptional interface {
	isPresentationOptions_DigestOptional()
}

type PresentationOptions_Digest struct {
	Digest *Digest `protobuf:"bytes,1400,opt,name=digest,proto3,oneof"`
}

func (*PresentationOptions_Digest) isPresentationOptions_DigestOptional() {}

func (m *PresentationOptions) GetDigestOptional() isPresentationOptions_DigestOptional {
	if m != nil {
		return m.DigestOptional
	}
	return nil
}

func (m *PresentationOptions) GetDigest() *Digest {
	if x, ok := m.GetDigestOptional().(*PresentationOptions_Digest); ok {
		return x.Digest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PresentationOptions) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PresentationOptions_Encoding)(nil),
		(*PresentationOptions_Compression)(nil),
		(*PresentationOptions_Digest)(nil),
	}
}

func init() {
	proto.RegisterType((*PresentationOptions)(nil), "atlas.PresentationOptions")
}

func init() { proto.RegisterFile("presentation_options.proto", fileDescriptor_b96e64fc87a45d1f) }

var fileDescriptor_b96e64fc87a45d1f = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0x4a, 0x2d,
	0x4e, 0xcd, 0x2b, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x8b, 0xcf, 0x2f, 0x00, 0x51, 0xc5, 0x7a, 0x05,
	0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x89, 0x25, 0x39, 0x89, 0xc5, 0x52, 0x82, 0xc9, 0xf9, 0xb9,
	0x20, 0x55, 0xc5, 0x99, 0xf9, 0x79, 0x10, 0x19, 0x29, 0x9e, 0x94, 0xcc, 0xf4, 0xd4, 0xe2, 0x12,
	0x28, 0x8f, 0x2f, 0x35, 0x2f, 0x39, 0x3f, 0x25, 0x33, 0x2f, 0x1d, 0xc2, 0x57, 0x7a, 0xc1, 0xc8,
	0x25, 0x1c, 0x80, 0x64, 0xac, 0x3f, 0xc4, 0x54, 0x21, 0x3d, 0x2e, 0x0e, 0x98, 0x4a, 0x89, 0x05,
	0x6c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xfc, 0x7a, 0x60, 0x3b, 0xf4, 0x5c, 0xa1, 0xe2, 0x1e, 0x0c,
	0x41, 0x70, 0x35, 0x42, 0xe6, 0x5c, 0xdc, 0x48, 0x56, 0x4b, 0xb4, 0xb0, 0x83, 0xb5, 0x08, 0x41,
	0xb5, 0x38, 0x23, 0xa4, 0x3c, 0x18, 0x83, 0x90, 0x55, 0x0a, 0x69, 0x70, 0xb1, 0x41, 0x1c, 0x28,
	0xf1, 0x83, 0x0b, 0xac, 0x87, 0x17, 0xaa, 0xc7, 0x05, 0x2c, 0xea, 0xc1, 0x14, 0x04, 0x95, 0x77,
	0x12, 0xe6, 0x12, 0x84, 0x59, 0x07, 0xf5, 0x7c, 0x62, 0x8e, 0x93, 0x18, 0x97, 0x08, 0x92, 0x69,
	0x08, 0x71, 0x41, 0x2e, 0x7e, 0x88, 0x36, 0xb8, 0x50, 0x12, 0x1b, 0xd8, 0xc7, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x92, 0x85, 0x9c, 0x9a, 0x47, 0x01, 0x00, 0x00,
}
