// source: report.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var metadata_pb = require('./metadata_pb.js');
goog.object.extend(proto, metadata_pb);
goog.exportSymbol('proto.atlas.Report', null, global);
goog.exportSymbol('proto.atlas.Report.HeaderOptionalCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.atlas.Report = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.atlas.Report.repeatedFields_, proto.atlas.Report.oneofGroups_);
};
goog.inherits(proto.atlas.Report, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.atlas.Report.displayName = 'proto.atlas.Report';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.atlas.Report.repeatedFields_ = [300];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.atlas.Report.oneofGroups_ = [[100]];

/**
 * @enum {number}
 */
proto.atlas.Report.HeaderOptionalCase = {
  HEADER_OPTIONAL_NOT_SET: 0,
  HEADER: 100
};

/**
 * @return {proto.atlas.Report.HeaderOptionalCase}
 */
proto.atlas.Report.prototype.getHeaderOptionalCase = function() {
  return /** @type {proto.atlas.Report.HeaderOptionalCase} */(jspb.Message.computeOneofCase(this, proto.atlas.Report.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.atlas.Report.prototype.toObject = function(opt_includeInstance) {
  return proto.atlas.Report.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.atlas.Report} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.atlas.Report.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && metadata_pb.Metadata.toObject(includeInstance, f),
    bytes: msg.getBytes_asB64(),
    childrenList: jspb.Message.toObjectList(msg.getChildrenList(),
    proto.atlas.Report.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.atlas.Report}
 */
proto.atlas.Report.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.atlas.Report;
  return proto.atlas.Report.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.atlas.Report} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.atlas.Report}
 */
proto.atlas.Report.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 100:
      var value = new metadata_pb.Metadata;
      reader.readMessage(value,metadata_pb.Metadata.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 200:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBytes(value);
      break;
    case 300:
      var value = new proto.atlas.Report;
      reader.readMessage(value,proto.atlas.Report.deserializeBinaryFromReader);
      msg.addChildren(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.atlas.Report.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.atlas.Report.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.atlas.Report} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.atlas.Report.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      100,
      f,
      metadata_pb.Metadata.serializeBinaryToWriter
    );
  }
  f = message.getBytes_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      200,
      f
    );
  }
  f = message.getChildrenList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      300,
      f,
      proto.atlas.Report.serializeBinaryToWriter
    );
  }
};


/**
 * optional Metadata header = 100;
 * @return {?proto.atlas.Metadata}
 */
proto.atlas.Report.prototype.getHeader = function() {
  return /** @type{?proto.atlas.Metadata} */ (
    jspb.Message.getWrapperField(this, metadata_pb.Metadata, 100));
};


/**
 * @param {?proto.atlas.Metadata|undefined} value
 * @return {!proto.atlas.Report} returns this
*/
proto.atlas.Report.prototype.setHeader = function(value) {
  return jspb.Message.setOneofWrapperField(this, 100, proto.atlas.Report.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.atlas.Report} returns this
 */
proto.atlas.Report.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.atlas.Report.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 100) != null;
};


/**
 * optional bytes bytes = 200;
 * @return {string}
 */
proto.atlas.Report.prototype.getBytes = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 200, ""));
};


/**
 * optional bytes bytes = 200;
 * This is a type-conversion wrapper around `getBytes()`
 * @return {string}
 */
proto.atlas.Report.prototype.getBytes_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBytes()));
};


/**
 * optional bytes bytes = 200;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBytes()`
 * @return {!Uint8Array}
 */
proto.atlas.Report.prototype.getBytes_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBytes()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.atlas.Report} returns this
 */
proto.atlas.Report.prototype.setBytes = function(value) {
  return jspb.Message.setProto3BytesField(this, 200, value);
};


/**
 * repeated Report children = 300;
 * @return {!Array<!proto.atlas.Report>}
 */
proto.atlas.Report.prototype.getChildrenList = function() {
  return /** @type{!Array<!proto.atlas.Report>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.atlas.Report, 300));
};


/**
 * @param {!Array<!proto.atlas.Report>} value
 * @return {!proto.atlas.Report} returns this
*/
proto.atlas.Report.prototype.setChildrenList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 300, value);
};


/**
 * @param {!proto.atlas.Report=} opt_value
 * @param {number=} opt_index
 * @return {!proto.atlas.Report}
 */
proto.atlas.Report.prototype.addChildren = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 300, opt_value, proto.atlas.Report, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.atlas.Report} returns this
 */
proto.atlas.Report.prototype.clearChildrenList = function() {
  return this.setChildrenList([]);
};


goog.object.extend(exports, proto.atlas);
