// Code generated by protoc-gen-go. DO NOT EDIT.
// source: report_multi.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReportMulti struct {
	// Types that are valid to be assigned to HeaderOptional:
	//	*ReportMulti_Header
	HeaderOptional       isReportMulti_HeaderOptional `protobuf_oneof:"header_optional"`
	Reports              []*Report                    `protobuf:"bytes,500,rep,name=reports,proto3" json:"reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ReportMulti) Reset()      { *m = ReportMulti{} }
func (*ReportMulti) ProtoMessage() {}
func (*ReportMulti) Descriptor() ([]byte, []int) {
	return fileDescriptor_cef930ad3d4dd6b7, []int{0}
}

func (m *ReportMulti) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportMulti.Unmarshal(m, b)
}
func (m *ReportMulti) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportMulti.Marshal(b, m, deterministic)
}
func (m *ReportMulti) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportMulti.Merge(m, src)
}
func (m *ReportMulti) XXX_Size() int {
	return xxx_messageInfo_ReportMulti.Size(m)
}
func (m *ReportMulti) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportMulti.DiscardUnknown(m)
}

var xxx_messageInfo_ReportMulti proto.InternalMessageInfo

type isReportMulti_HeaderOptional interface {
	isReportMulti_HeaderOptional()
}

type ReportMulti_Header struct {
	Header *Metadata `protobuf:"bytes,100,opt,name=header,proto3,oneof"`
}

func (*ReportMulti_Header) isReportMulti_HeaderOptional() {}

func (m *ReportMulti) GetHeaderOptional() isReportMulti_HeaderOptional {
	if m != nil {
		return m.HeaderOptional
	}
	return nil
}

func (m *ReportMulti) GetHeader() *Metadata {
	if x, ok := m.GetHeaderOptional().(*ReportMulti_Header); ok {
		return x.Header
	}
	return nil
}

func (m *ReportMulti) GetReports() []*Report {
	if m != nil {
		return m.Reports
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ReportMulti) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ReportMulti_Header)(nil),
	}
}

func init() {
	proto.RegisterType((*ReportMulti)(nil), "atlas.ReportMulti")
}

func init() { proto.RegisterFile("report_multi.proto", fileDescriptor_cef930ad3d4dd6b7) }

var fileDescriptor_cef930ad3d4dd6b7 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4a, 0x2d, 0xc8,
	0x2f, 0x2a, 0x89, 0xcf, 0x2d, 0xcd, 0x29, 0xc9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x4d, 0x2c, 0xc9, 0x49, 0x2c, 0x96, 0xe2, 0xcb, 0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c, 0x49, 0x84,
	0x08, 0x4b, 0xf1, 0x40, 0x94, 0x42, 0x78, 0x4a, 0xa5, 0x5c, 0xdc, 0x41, 0x60, 0xbe, 0x2f, 0x48,
	0xa7, 0x90, 0x26, 0x17, 0x5b, 0x46, 0x6a, 0x62, 0x4a, 0x6a, 0x91, 0x44, 0x8a, 0x02, 0xa3, 0x06,
	0xb7, 0x11, 0xbf, 0x1e, 0xd8, 0x10, 0x3d, 0x5f, 0xa8, 0x19, 0x1e, 0x0c, 0x41, 0x50, 0x05, 0x42,
	0x1a, 0x5c, 0xec, 0x10, 0x93, 0x8a, 0x25, 0xbe, 0x30, 0x2b, 0x30, 0x6b, 0x70, 0x1b, 0xf1, 0x42,
	0x15, 0x43, 0x0c, 0x0c, 0x82, 0x49, 0x3b, 0x09, 0x72, 0xf1, 0x43, 0xf4, 0xc4, 0xe7, 0x17, 0x94,
	0x64, 0xe6, 0xe7, 0x25, 0xe6, 0x24, 0xb1, 0x81, 0x6d, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xc0, 0xa3, 0x93, 0x0c, 0xb8, 0x00, 0x00, 0x00,
}
