// Code generated by protoc-gen-go. DO NOT EDIT.
// source: report_request.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReportRequest struct {
	Header               *Metadata `protobuf:"bytes,100,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReportRequest) Reset()      { *m = ReportRequest{} }
func (*ReportRequest) ProtoMessage() {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_668f05bfed3d581a, []int{0}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetHeader() *Metadata {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*ReportRequest)(nil), "atlas.ReportRequest")
}

func init() { proto.RegisterFile("report_request.proto", fileDescriptor_668f05bfed3d581a) }

var fileDescriptor_668f05bfed3d581a = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4a, 0x2d, 0xc8,
	0x2f, 0x2a, 0x89, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x4d, 0x2c, 0xc9, 0x49, 0x2c, 0x96, 0xe2, 0xcb, 0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c,
	0x49, 0x84, 0x08, 0x2b, 0x59, 0x70, 0xf1, 0x06, 0x81, 0x95, 0x07, 0x41, 0x54, 0x0b, 0xa9, 0x73,
	0xb1, 0x65, 0xa4, 0x26, 0xa6, 0xa4, 0x16, 0x49, 0xa4, 0x28, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xeb,
	0x81, 0x35, 0xea, 0xf9, 0x42, 0xf5, 0x05, 0x41, 0xa5, 0x93, 0xd8, 0xc0, 0x06, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xb0, 0x10, 0xaf, 0xa9, 0x6f, 0x00, 0x00, 0x00,
}
