// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status_request_multi.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusRequestMulti struct {
	// Types that are valid to be assigned to DomainOptional:
	//	*StatusRequestMulti_Domain
	DomainOptional isStatusRequestMulti_DomainOptional `protobuf_oneof:"domain_optional"`
	// Types that are valid to be assigned to ModeOptional:
	//	*StatusRequestMulti_Mode
	ModeOptional         isStatusRequestMulti_ModeOptional `protobuf_oneof:"mode_optional"`
	Entities             []*StatusRequest                  `protobuf:"bytes,300,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *StatusRequestMulti) Reset()      { *m = StatusRequestMulti{} }
func (*StatusRequestMulti) ProtoMessage() {}
func (*StatusRequestMulti) Descriptor() ([]byte, []int) {
	return fileDescriptor_53d95ec84ec0cd32, []int{0}
}

func (m *StatusRequestMulti) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequestMulti.Unmarshal(m, b)
}
func (m *StatusRequestMulti) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequestMulti.Marshal(b, m, deterministic)
}
func (m *StatusRequestMulti) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequestMulti.Merge(m, src)
}
func (m *StatusRequestMulti) XXX_Size() int {
	return xxx_messageInfo_StatusRequestMulti.Size(m)
}
func (m *StatusRequestMulti) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequestMulti.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequestMulti proto.InternalMessageInfo

type isStatusRequestMulti_DomainOptional interface {
	isStatusRequestMulti_DomainOptional()
}

type StatusRequestMulti_Domain struct {
	Domain *Domain `protobuf:"bytes,100,opt,name=domain,proto3,oneof"`
}

func (*StatusRequestMulti_Domain) isStatusRequestMulti_DomainOptional() {}

func (m *StatusRequestMulti) GetDomainOptional() isStatusRequestMulti_DomainOptional {
	if m != nil {
		return m.DomainOptional
	}
	return nil
}

func (m *StatusRequestMulti) GetDomain() *Domain {
	if x, ok := m.GetDomainOptional().(*StatusRequestMulti_Domain); ok {
		return x.Domain
	}
	return nil
}

type isStatusRequestMulti_ModeOptional interface {
	isStatusRequestMulti_ModeOptional()
}

type StatusRequestMulti_Mode struct {
	Mode StatusRequestMode `protobuf:"varint,200,opt,name=mode,proto3,enum=atlas.StatusRequestMode,oneof"`
}

func (*StatusRequestMulti_Mode) isStatusRequestMulti_ModeOptional() {}

func (m *StatusRequestMulti) GetModeOptional() isStatusRequestMulti_ModeOptional {
	if m != nil {
		return m.ModeOptional
	}
	return nil
}

func (m *StatusRequestMulti) GetMode() StatusRequestMode {
	if x, ok := m.GetModeOptional().(*StatusRequestMulti_Mode); ok {
		return x.Mode
	}
	return StatusRequestMode_RESERVED
}

func (m *StatusRequestMulti) GetEntities() []*StatusRequest {
	if m != nil {
		return m.Entities
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StatusRequestMulti) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StatusRequestMulti_Domain)(nil),
		(*StatusRequestMulti_Mode)(nil),
	}
}

func init() {
	proto.RegisterType((*StatusRequestMulti)(nil), "atlas.StatusRequestMulti")
}

func init() { proto.RegisterFile("status_request_multi.proto", fileDescriptor_53d95ec84ec0cd32) }

var fileDescriptor_53d95ec84ec0cd32 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0x8e, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x89, 0xcf, 0x2d, 0xcd, 0x29, 0xc9,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2c, 0xc9, 0x49, 0x2c, 0x96, 0xe2, 0x49,
	0xc9, 0xcf, 0x4d, 0xcc, 0xcc, 0x83, 0x08, 0x4a, 0x89, 0xa0, 0x6a, 0x80, 0x8a, 0x4a, 0xa2, 0x1b,
	0x93, 0x9f, 0x92, 0x0a, 0x91, 0x52, 0x3a, 0xca, 0xc8, 0x25, 0x14, 0x0c, 0x96, 0x0d, 0x82, 0x48,
	0xfa, 0x82, 0xac, 0x10, 0x52, 0xe7, 0x62, 0x83, 0x98, 0x2b, 0x91, 0xa2, 0xc0, 0xa8, 0xc1, 0x6d,
	0xc4, 0xab, 0x07, 0xb6, 0x4d, 0xcf, 0x05, 0x2c, 0xe8, 0xc1, 0x10, 0x04, 0x95, 0x16, 0xd2, 0xe7,
	0x62, 0x01, 0x99, 0x26, 0x71, 0x82, 0x51, 0x81, 0x51, 0x83, 0xcf, 0x48, 0x02, 0xaa, 0x0e, 0xd5,
	0xc8, 0xfc, 0x94, 0x54, 0x0f, 0xc6, 0x20, 0xb0, 0x42, 0x21, 0x43, 0x2e, 0x8e, 0xd4, 0xbc, 0x92,
	0xcc, 0x92, 0xcc, 0xd4, 0x62, 0x89, 0x35, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x22, 0xd8, 0x34,
	0x05, 0xc1, 0x95, 0x39, 0x09, 0x72, 0xf1, 0x43, 0x6c, 0x8b, 0xcf, 0x2f, 0x28, 0xc9, 0xcc, 0xcf,
	0x4b, 0xcc, 0x71, 0xe2, 0xe7, 0xe2, 0x05, 0x99, 0x06, 0x17, 0x48, 0x62, 0x03, 0x7b, 0xc7, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x65, 0x81, 0x4f, 0x32, 0x01, 0x00, 0x00,
}
