// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status_multi.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// StatusMulti represents status of multiple object(s)
type StatusMulti struct {
	// Types that are valid to be assigned to HeaderOptional:
	//	*StatusMulti_Header
	HeaderOptional       isStatusMulti_HeaderOptional `protobuf_oneof:"header_optional"`
	Statuses             []*Status                    `protobuf:"bytes,200,rep,name=statuses,proto3" json:"statuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *StatusMulti) Reset()      { *m = StatusMulti{} }
func (*StatusMulti) ProtoMessage() {}
func (*StatusMulti) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fed343894600788, []int{0}
}

func (m *StatusMulti) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusMulti.Unmarshal(m, b)
}
func (m *StatusMulti) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusMulti.Marshal(b, m, deterministic)
}
func (m *StatusMulti) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusMulti.Merge(m, src)
}
func (m *StatusMulti) XXX_Size() int {
	return xxx_messageInfo_StatusMulti.Size(m)
}
func (m *StatusMulti) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusMulti.DiscardUnknown(m)
}

var xxx_messageInfo_StatusMulti proto.InternalMessageInfo

type isStatusMulti_HeaderOptional interface {
	isStatusMulti_HeaderOptional()
}

type StatusMulti_Header struct {
	Header *Metadata `protobuf:"bytes,100,opt,name=header,proto3,oneof"`
}

func (*StatusMulti_Header) isStatusMulti_HeaderOptional() {}

func (m *StatusMulti) GetHeaderOptional() isStatusMulti_HeaderOptional {
	if m != nil {
		return m.HeaderOptional
	}
	return nil
}

func (m *StatusMulti) GetHeader() *Metadata {
	if x, ok := m.GetHeaderOptional().(*StatusMulti_Header); ok {
		return x.Header
	}
	return nil
}

func (m *StatusMulti) GetStatuses() []*Status {
	if m != nil {
		return m.Statuses
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StatusMulti) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StatusMulti_Header)(nil),
	}
}

func init() {
	proto.RegisterType((*StatusMulti)(nil), "atlas.StatusMulti")
}

func init() { proto.RegisterFile("status_multi.proto", fileDescriptor_7fed343894600788) }

var fileDescriptor_7fed343894600788 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0x8e, 0xcf, 0x2d, 0xcd, 0x29, 0xc9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x4d, 0x2c, 0xc9, 0x49, 0x2c, 0x96, 0xe2, 0xcb, 0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c, 0x49, 0x84,
	0x08, 0x4b, 0xf1, 0x40, 0x94, 0x42, 0x78, 0x4a, 0xe5, 0x5c, 0xdc, 0xc1, 0x60, 0xbe, 0x2f, 0x48,
	0xa7, 0x90, 0x26, 0x17, 0x5b, 0x46, 0x6a, 0x62, 0x4a, 0x6a, 0x91, 0x44, 0x8a, 0x02, 0xa3, 0x06,
	0xb7, 0x11, 0xbf, 0x1e, 0xd8, 0x10, 0x3d, 0x5f, 0xa8, 0x19, 0x1e, 0x0c, 0x41, 0x50, 0x05, 0x42,
	0x5a, 0x5c, 0x1c, 0x10, 0x93, 0x52, 0x8b, 0x25, 0x4e, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0xf1,
	0x42, 0x55, 0x43, 0x4c, 0x0c, 0x82, 0xcb, 0x3b, 0x09, 0x72, 0xf1, 0x43, 0x74, 0xc5, 0xe7, 0x17,
	0x94, 0x64, 0xe6, 0xe7, 0x25, 0xe6, 0x24, 0xb1, 0x81, 0xed, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xd9, 0x00, 0x95, 0x94, 0xba, 0x00, 0x00, 0x00,
}
