// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	// Header of the task
	Header *Metadata `protobuf:"bytes,100,opt,name=header,proto3" json:"header,omitempty"`
	// Optional. Any arbitrary sequence of bytes no longer than 2^32
	Bytes []byte `protobuf:"bytes,200,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// Optional. Multiple task's subjects.
	Subjects []*Metadata `protobuf:"bytes,300,rep,name=subjects,proto3" json:"subjects,omitempty"`
	// Optional. Recursive chain of tasks
	Parents []*Task `protobuf:"bytes,400,rep,name=parents,proto3" json:"parents,omitempty"`
	// Optional. Recursive chain of tasks
	Children             []*Task  `protobuf:"bytes,500,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()      { *m = Task{} }
func (*Task) ProtoMessage() {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetHeader() *Metadata {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Task) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *Task) GetSubjects() []*Metadata {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func (m *Task) GetParents() []*Task {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *Task) GetChildren() []*Task {
	if m != nil {
		return m.Children
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "atlas.Task")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2c, 0xce,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2c, 0xc9, 0x49, 0x2c, 0x96, 0xe2, 0xcb,
	0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c, 0x49, 0x84, 0x08, 0x2b, 0x1d, 0x63, 0xe4, 0x62, 0x09, 0x49,
	0x2c, 0xce, 0x16, 0x52, 0xe7, 0x62, 0xcb, 0x48, 0x4d, 0x4c, 0x49, 0x2d, 0x92, 0x48, 0x51, 0x60,
	0xd4, 0xe0, 0x36, 0xe2, 0xd7, 0x03, 0x6b, 0xd0, 0xf3, 0x85, 0xaa, 0x0f, 0x82, 0x4a, 0x0b, 0x89,
	0x72, 0xb1, 0x26, 0x55, 0x96, 0xa4, 0x16, 0x4b, 0x9c, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x82,
	0xf0, 0x84, 0x74, 0xb8, 0x38, 0x8a, 0x4b, 0x93, 0xb2, 0x52, 0x93, 0x4b, 0x8a, 0x25, 0xd6, 0x30,
	0x29, 0x30, 0x63, 0x33, 0x02, 0xae, 0x42, 0x48, 0x8d, 0x8b, 0xbd, 0x20, 0xb1, 0x28, 0x35, 0xaf,
	0xa4, 0x58, 0x62, 0x02, 0x33, 0x58, 0x31, 0x37, 0x54, 0x31, 0xc8, 0x31, 0x41, 0x30, 0x49, 0x21,
	0x0d, 0x2e, 0x8e, 0xe4, 0x8c, 0xcc, 0x9c, 0x94, 0xa2, 0xd4, 0x3c, 0x89, 0x2f, 0x58, 0x14, 0xc2,
	0x65, 0x93, 0xd8, 0xc0, 0xfe, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xf0, 0x7d, 0x63,
	0xf4, 0x00, 0x00, 0x00,
}
