// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type_file_fingerprint.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DigestType int32

const (
	// Due to first enum value has to be zero in proto3
	DigestType_DIGEST_RESERVED    DigestType = 0
	DigestType_DIGEST_UNSPECIFIED DigestType = 100
	DigestType_DIGEST_MD5         DigestType = 200
	DigestType_DIGEST_SHA256      DigestType = 300
)

var DigestType_name = map[int32]string{
	0:   "DIGEST_RESERVED",
	100: "DIGEST_UNSPECIFIED",
	200: "DIGEST_MD5",
	300: "DIGEST_SHA256",
}

var DigestType_value = map[string]int32{
	"DIGEST_RESERVED":    0,
	"DIGEST_UNSPECIFIED": 100,
	"DIGEST_MD5":         200,
	"DIGEST_SHA256":      300,
}

func (x DigestType) String() string {
	return proto.EnumName(DigestType_name, int32(x))
}

func (DigestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e00ecc0e47f42553, []int{0}
}

type Domain struct {
	Name                 string   `protobuf:"bytes,100,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Domain) Reset()         { *m = Domain{} }
func (m *Domain) String() string { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()    {}
func (*Domain) Descriptor() ([]byte, []int) {
	return fileDescriptor_e00ecc0e47f42553, []int{0}
}

func (m *Domain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Domain.Unmarshal(m, b)
}
func (m *Domain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Domain.Marshal(b, m, deterministic)
}
func (m *Domain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Domain.Merge(m, src)
}
func (m *Domain) XXX_Size() int {
	return xxx_messageInfo_Domain.Size(m)
}
func (m *Domain) XXX_DiscardUnknown() {
	xxx_messageInfo_Domain.DiscardUnknown(m)
}

var xxx_messageInfo_Domain proto.InternalMessageInfo

func (m *Domain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FileFingerprint struct {
	Domain               *Domain    `protobuf:"bytes,100,opt,name=domain,proto3" json:"domain,omitempty"`
	DigestType           DigestType `protobuf:"varint,200,opt,name=digest_type,json=digestType,proto3,enum=atlas.DigestType" json:"digest_type,omitempty"`
	Digest               []byte     `protobuf:"bytes,300,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FileFingerprint) Reset()         { *m = FileFingerprint{} }
func (m *FileFingerprint) String() string { return proto.CompactTextString(m) }
func (*FileFingerprint) ProtoMessage()    {}
func (*FileFingerprint) Descriptor() ([]byte, []int) {
	return fileDescriptor_e00ecc0e47f42553, []int{1}
}

func (m *FileFingerprint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileFingerprint.Unmarshal(m, b)
}
func (m *FileFingerprint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileFingerprint.Marshal(b, m, deterministic)
}
func (m *FileFingerprint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileFingerprint.Merge(m, src)
}
func (m *FileFingerprint) XXX_Size() int {
	return xxx_messageInfo_FileFingerprint.Size(m)
}
func (m *FileFingerprint) XXX_DiscardUnknown() {
	xxx_messageInfo_FileFingerprint.DiscardUnknown(m)
}

var xxx_messageInfo_FileFingerprint proto.InternalMessageInfo

func (m *FileFingerprint) GetDomain() *Domain {
	if m != nil {
		return m.Domain
	}
	return nil
}

func (m *FileFingerprint) GetDigestType() DigestType {
	if m != nil {
		return m.DigestType
	}
	return DigestType_DIGEST_RESERVED
}

func (m *FileFingerprint) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func init() {
	proto.RegisterEnum("atlas.DigestType", DigestType_name, DigestType_value)
	proto.RegisterType((*Domain)(nil), "atlas.Domain")
	proto.RegisterType((*FileFingerprint)(nil), "atlas.FileFingerprint")
}

func init() { proto.RegisterFile("type_file_fingerprint.proto", fileDescriptor_e00ecc0e47f42553) }

var fileDescriptor_e00ecc0e47f42553 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x50, 0xcf, 0x4a, 0xc3, 0x30,
	0x18, 0x37, 0x43, 0x0b, 0x7e, 0x73, 0xb6, 0x7e, 0x82, 0x16, 0xf4, 0x50, 0x06, 0x42, 0xf1, 0xd0,
	0x43, 0xc7, 0xbc, 0x8b, 0x49, 0xb5, 0x07, 0x45, 0xd2, 0xe9, 0xd1, 0x52, 0x49, 0x1c, 0x81, 0x2e,
	0x0d, 0x5d, 0x2e, 0x7b, 0x01, 0x9f, 0x66, 0x0f, 0xb2, 0xc7, 0x92, 0x65, 0x71, 0xbb, 0x84, 0xdf,
	0x7f, 0xc2, 0x07, 0x37, 0x76, 0x65, 0x64, 0xfd, 0xa3, 0xda, 0xed, 0xa3, 0xe7, 0xb2, 0x37, 0xbd,
	0xd2, 0x36, 0x33, 0x7d, 0x67, 0x3b, 0x3c, 0x69, 0x6c, 0xdb, 0x2c, 0xc7, 0xb7, 0x10, 0xd0, 0x6e,
	0xd1, 0x28, 0x8d, 0x08, 0xc7, 0xba, 0x59, 0xc8, 0x58, 0x24, 0x24, 0x3d, 0xe5, 0x0e, 0x8f, 0x7f,
	0x09, 0x84, 0x85, 0x6a, 0x65, 0x71, 0xa8, 0xe3, 0x1d, 0x04, 0xc2, 0x35, 0x5c, 0x72, 0x98, 0x8f,
	0x32, 0xb7, 0x94, 0xed, 0x66, 0xb8, 0x37, 0x71, 0x02, 0x43, 0xa1, 0xe6, 0x72, 0x69, 0xeb, 0xed,
	0x2f, 0xe2, 0x0d, 0x49, 0x48, 0x7a, 0x9e, 0x5f, 0xfc, 0x87, 0x9d, 0x35, 0x5b, 0x19, 0xc9, 0x41,
	0xec, 0x31, 0x5e, 0x43, 0xb0, 0x63, 0xf1, 0x7a, 0x90, 0x90, 0xf4, 0x8c, 0x7b, 0x7a, 0xff, 0x05,
	0x70, 0xa8, 0xe0, 0x25, 0x84, 0xb4, 0x7c, 0x66, 0xd5, 0xac, 0xe6, 0xac, 0x62, 0xfc, 0x93, 0xd1,
	0xe8, 0x08, 0xaf, 0x00, 0xbd, 0xf8, 0xf1, 0x56, 0xbd, 0xb3, 0xa7, 0xb2, 0x28, 0x19, 0x8d, 0x04,
	0x86, 0x00, 0x5e, 0x7f, 0xa5, 0xd3, 0x68, 0x43, 0x10, 0x61, 0xe4, 0x85, 0xea, 0xe5, 0x31, 0x9f,
	0x3e, 0x44, 0xeb, 0xc1, 0x77, 0xe0, 0x8e, 0x32, 0xf9, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x59, 0x64,
	0xa0, 0xfa, 0x33, 0x01, 0x00, 0x00,
}
