// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type_status_request.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// StatusRequest represents status request of the object(s)
type StatusRequest struct {
	// Entity which status is requested
	Entity *Entity `protobuf:"bytes,100,opt,name=entity,proto3" json:"entity,omitempty"`
	// Digest of entity to get status about
	Digest               *Digest  `protobuf:"bytes,200,opt,name=digest,proto3" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be84576e251c0653, []int{0}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

func (m *StatusRequest) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *StatusRequest) GetDigest() *Digest {
	if m != nil {
		return m.Digest
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "atlas.StatusRequest")
}

func init() { proto.RegisterFile("type_status_request.proto", fileDescriptor_be84576e251c0653) }

var fileDescriptor_be84576e251c0653 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0xa9, 0x2c, 0x48,
	0x8d, 0x2f, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x8e, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2c, 0xc9, 0x49, 0x2c, 0x96, 0x12, 0x04, 0xab,
	0x48, 0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0x84, 0xc8, 0x40, 0x85, 0x52, 0x32, 0xd3, 0xe1, 0x8a, 0x95,
	0xe2, 0xb8, 0x78, 0x83, 0xc1, 0x86, 0x04, 0x41, 0xcc, 0x10, 0x52, 0xe5, 0x62, 0x83, 0xe8, 0x91,
	0x48, 0x51, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd5, 0x03, 0x1b, 0xa7, 0xe7, 0x0a, 0x16, 0x0c, 0x82,
	0x4a, 0x0a, 0xa9, 0x71, 0xb1, 0x41, 0xcc, 0x91, 0x38, 0xc1, 0x88, 0xa2, 0xce, 0x05, 0x2c, 0x1a,
	0x04, 0x95, 0x4d, 0x62, 0x03, 0x5b, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x44, 0xd7, 0xe9,
	0x9a, 0xb0, 0x00, 0x00, 0x00,
}
