// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type_file_status.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileStatusType int32

const (
	// Due to first enum value has to be zero in proto3
	FileStatusType_FILE_STATUS_RESERVED    FileStatusType = 0
	FileStatusType_FILE_STATUS_UNSPECIFIED FileStatusType = 100
	FileStatusType_FILE_STATUS_NOT_FOUND   FileStatusType = 200
	FileStatusType_FILE_STATUS_FOUND       FileStatusType = 300
)

var FileStatusType_name = map[int32]string{
	0:   "FILE_STATUS_RESERVED",
	100: "FILE_STATUS_UNSPECIFIED",
	200: "FILE_STATUS_NOT_FOUND",
	300: "FILE_STATUS_FOUND",
}

var FileStatusType_value = map[string]int32{
	"FILE_STATUS_RESERVED":    0,
	"FILE_STATUS_UNSPECIFIED": 100,
	"FILE_STATUS_NOT_FOUND":   200,
	"FILE_STATUS_FOUND":       300,
}

func (x FileStatusType) String() string {
	return proto.EnumName(FileStatusType_name, int32(x))
}

func (FileStatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c565564c84995262, []int{0}
}

type FileStatus1 struct {
	Status               FileStatusType `protobuf:"varint,100,opt,name=status,proto3,enum=atlas.FileStatusType" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FileStatus1) Reset()         { *m = FileStatus1{} }
func (m *FileStatus1) String() string { return proto.CompactTextString(m) }
func (*FileStatus1) ProtoMessage()    {}
func (*FileStatus1) Descriptor() ([]byte, []int) {
	return fileDescriptor_c565564c84995262, []int{0}
}

func (m *FileStatus1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileStatus1.Unmarshal(m, b)
}
func (m *FileStatus1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileStatus1.Marshal(b, m, deterministic)
}
func (m *FileStatus1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileStatus1.Merge(m, src)
}
func (m *FileStatus1) XXX_Size() int {
	return xxx_messageInfo_FileStatus1.Size(m)
}
func (m *FileStatus1) XXX_DiscardUnknown() {
	xxx_messageInfo_FileStatus1.DiscardUnknown(m)
}

var xxx_messageInfo_FileStatus1 proto.InternalMessageInfo

func (m *FileStatus1) GetStatus() FileStatusType {
	if m != nil {
		return m.Status
	}
	return FileStatusType_FILE_STATUS_RESERVED
}

func init() {
	proto.RegisterEnum("atlas.FileStatusType", FileStatusType_name, FileStatusType_value)
	proto.RegisterType((*FileStatus1)(nil), "atlas.FileStatus1")
}

func init() { proto.RegisterFile("type_file_status.proto", fileDescriptor_c565564c84995262) }

var fileDescriptor_c565564c84995262 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0xa9, 0x2c, 0x48,
	0x8d, 0x4f, 0xcb, 0xcc, 0x49, 0x8d, 0x2f, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0xd6, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x2c, 0xc9, 0x49, 0x2c, 0x56, 0xb2, 0xe1, 0xe2, 0x76, 0xcb, 0xcc,
	0x49, 0x0d, 0x06, 0x4b, 0x19, 0x0a, 0xe9, 0x72, 0xb1, 0x41, 0x54, 0x49, 0xa4, 0x28, 0x30, 0x6a,
	0xf0, 0x19, 0x89, 0xea, 0x81, 0x95, 0xe9, 0x21, 0xd4, 0x84, 0x54, 0x16, 0xa4, 0x06, 0x41, 0x15,
	0x69, 0x55, 0x73, 0xf1, 0xa1, 0xca, 0x08, 0x49, 0x70, 0x89, 0xb8, 0x79, 0xfa, 0xb8, 0xc6, 0x07,
	0x87, 0x38, 0x86, 0x84, 0x06, 0xc7, 0x07, 0xb9, 0x06, 0xbb, 0x06, 0x85, 0xb9, 0xba, 0x08, 0x30,
	0x08, 0x49, 0x73, 0x89, 0x23, 0xcb, 0x84, 0xfa, 0x05, 0x07, 0xb8, 0x3a, 0x7b, 0xba, 0x79, 0xba,
	0xba, 0x08, 0xa4, 0x08, 0x49, 0x71, 0x89, 0x22, 0x4b, 0xfa, 0xf9, 0x87, 0xc4, 0xbb, 0xf9, 0x87,
	0xfa, 0xb9, 0x08, 0x9c, 0x60, 0x14, 0x12, 0xe3, 0x12, 0x44, 0x96, 0x83, 0x88, 0xaf, 0x61, 0x4a,
	0x62, 0x03, 0x7b, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x42, 0x85, 0x87, 0x4c, 0xe2, 0x00,
	0x00, 0x00,
}
