// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type_metadata.proto

package atlas

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// MetadataType presents type of all metadata in the system
type MetadataType int32

const (
	// Due to first enum value has to be zero in proto3
	MetadataType_METADATA_RESERVED MetadataType = 0
)

var MetadataType_name = map[int32]string{
	0: "METADATA_RESERVED",
}

var MetadataType_value = map[string]int32{
	"METADATA_RESERVED": 0,
}

func (x MetadataType) String() string {
	return proto.EnumName(MetadataType_name, int32(x))
}

func (MetadataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6b5234c8ffbbe006, []int{0}
}

// Metadata describes metadata of the object
type Metadata struct {
	// Types that are valid to be assigned to TypeOptional:
	//	*Metadata_Type
	TypeOptional isMetadata_TypeOptional `protobuf_oneof:"type_optional"`
	// Types that are valid to be assigned to NameOptional:
	//	*Metadata_Name
	NameOptional isMetadata_NameOptional `protobuf_oneof:"name_optional"`
	// Types that are valid to be assigned to VersionOptional:
	//	*Metadata_Version
	VersionOptional isMetadata_VersionOptional `protobuf_oneof:"version_optional"`
	// Types that are valid to be assigned to UserIdOptional:
	//	*Metadata_UserId
	UserIdOptional isMetadata_UserIdOptional `protobuf_oneof:"user_id_optional"`
	// Types that are valid to be assigned to IdOptional:
	//	*Metadata_Id
	IdOptional isMetadata_IdOptional `protobuf_oneof:"id_optional"`
	// Types that are valid to be assigned to ReferenceIdOptional:
	//	*Metadata_ReferenceId
	ReferenceIdOptional isMetadata_ReferenceIdOptional `protobuf_oneof:"reference_id_optional"`
	// Types that are valid to be assigned to TimestampOptional:
	//	*Metadata_Ts
	TimestampOptional isMetadata_TimestampOptional `protobuf_oneof:"timestamp_optional"`
	// Types that are valid to be assigned to EncodingOptional:
	//	*Metadata_Encoding
	EncodingOptional isMetadata_EncodingOptional `protobuf_oneof:"encoding_optional"`
	// Types that are valid to be assigned to CompressionOptional:
	//	*Metadata_Compression
	CompressionOptional isMetadata_CompressionOptional `protobuf_oneof:"compression_optional"`
	// Types that are valid to be assigned to FilenameOptional:
	//	*Metadata_Filename
	FilenameOptional isMetadata_FilenameOptional `protobuf_oneof:"filename_optional"`
	// Types that are valid to be assigned to UrlOptional:
	//	*Metadata_Url
	UrlOptional isMetadata_UrlOptional `protobuf_oneof:"url_optional"`
	// Types that are valid to be assigned to S3AddressOptional:
	//	*Metadata_S3Address
	S3AddressOptional isMetadata_S3AddressOptional `protobuf_oneof:"s3address_optional"`
	// Types that are valid to be assigned to DomainOptional:
	//	*Metadata_Domain
	DomainOptional isMetadata_DomainOptional `protobuf_oneof:"domain_optional"`
	// Types that are valid to be assigned to DigestOptional:
	//	*Metadata_Digest
	DigestOptional isMetadata_DigestOptional `protobuf_oneof:"digest_optional"`
	// Types that are valid to be assigned to DescriptionOptional:
	//	*Metadata_Description
	DescriptionOptional isMetadata_DescriptionOptional `protobuf_oneof:"description_optional"`
	// Types that are valid to be assigned to LenOptional:
	//	*Metadata_Len
	LenOptional isMetadata_LenOptional `protobuf_oneof:"len_optional"`
	// Types that are valid to be assigned to OffsetOptional:
	//	*Metadata_Offset
	OffsetOptional isMetadata_OffsetOptional `protobuf_oneof:"offset_optional"`
	// Types that are valid to be assigned to LastOptional:
	//	*Metadata_Last
	LastOptional         isMetadata_LastOptional `protobuf_oneof:"last_optional"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b5234c8ffbbe006, []int{0}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

type isMetadata_TypeOptional interface {
	isMetadata_TypeOptional()
}

type Metadata_Type struct {
	Type int32 `protobuf:"varint,100,opt,name=type,proto3,oneof"`
}

func (*Metadata_Type) isMetadata_TypeOptional() {}

func (m *Metadata) GetTypeOptional() isMetadata_TypeOptional {
	if m != nil {
		return m.TypeOptional
	}
	return nil
}

func (m *Metadata) GetType() int32 {
	if x, ok := m.GetTypeOptional().(*Metadata_Type); ok {
		return x.Type
	}
	return 0
}

type isMetadata_NameOptional interface {
	isMetadata_NameOptional()
}

type Metadata_Name struct {
	Name string `protobuf:"bytes,200,opt,name=name,proto3,oneof"`
}

func (*Metadata_Name) isMetadata_NameOptional() {}

func (m *Metadata) GetNameOptional() isMetadata_NameOptional {
	if m != nil {
		return m.NameOptional
	}
	return nil
}

func (m *Metadata) GetName() string {
	if x, ok := m.GetNameOptional().(*Metadata_Name); ok {
		return x.Name
	}
	return ""
}

type isMetadata_VersionOptional interface {
	isMetadata_VersionOptional()
}

type Metadata_Version struct {
	Version int32 `protobuf:"varint,300,opt,name=version,proto3,oneof"`
}

func (*Metadata_Version) isMetadata_VersionOptional() {}

func (m *Metadata) GetVersionOptional() isMetadata_VersionOptional {
	if m != nil {
		return m.VersionOptional
	}
	return nil
}

func (m *Metadata) GetVersion() int32 {
	if x, ok := m.GetVersionOptional().(*Metadata_Version); ok {
		return x.Version
	}
	return 0
}

type isMetadata_UserIdOptional interface {
	isMetadata_UserIdOptional()
}

type Metadata_UserId struct {
	UserId *UserID `protobuf:"bytes,400,opt,name=user_id,json=userId,proto3,oneof"`
}

func (*Metadata_UserId) isMetadata_UserIdOptional() {}

func (m *Metadata) GetUserIdOptional() isMetadata_UserIdOptional {
	if m != nil {
		return m.UserIdOptional
	}
	return nil
}

func (m *Metadata) GetUserId() *UserID {
	if x, ok := m.GetUserIdOptional().(*Metadata_UserId); ok {
		return x.UserId
	}
	return nil
}

type isMetadata_IdOptional interface {
	isMetadata_IdOptional()
}

type Metadata_Id struct {
	Id *UUID `protobuf:"bytes,500,opt,name=id,proto3,oneof"`
}

func (*Metadata_Id) isMetadata_IdOptional() {}

func (m *Metadata) GetIdOptional() isMetadata_IdOptional {
	if m != nil {
		return m.IdOptional
	}
	return nil
}

func (m *Metadata) GetId() *UUID {
	if x, ok := m.GetIdOptional().(*Metadata_Id); ok {
		return x.Id
	}
	return nil
}

type isMetadata_ReferenceIdOptional interface {
	isMetadata_ReferenceIdOptional()
}

type Metadata_ReferenceId struct {
	ReferenceId *UUID `protobuf:"bytes,600,opt,name=reference_id,json=referenceId,proto3,oneof"`
}

func (*Metadata_ReferenceId) isMetadata_ReferenceIdOptional() {}

func (m *Metadata) GetReferenceIdOptional() isMetadata_ReferenceIdOptional {
	if m != nil {
		return m.ReferenceIdOptional
	}
	return nil
}

func (m *Metadata) GetReferenceId() *UUID {
	if x, ok := m.GetReferenceIdOptional().(*Metadata_ReferenceId); ok {
		return x.ReferenceId
	}
	return nil
}

type isMetadata_TimestampOptional interface {
	isMetadata_TimestampOptional()
}

type Metadata_Ts struct {
	Ts *timestamp.Timestamp `protobuf:"bytes,700,opt,name=ts,proto3,oneof"`
}

func (*Metadata_Ts) isMetadata_TimestampOptional() {}

func (m *Metadata) GetTimestampOptional() isMetadata_TimestampOptional {
	if m != nil {
		return m.TimestampOptional
	}
	return nil
}

func (m *Metadata) GetTs() *timestamp.Timestamp {
	if x, ok := m.GetTimestampOptional().(*Metadata_Ts); ok {
		return x.Ts
	}
	return nil
}

type isMetadata_EncodingOptional interface {
	isMetadata_EncodingOptional()
}

type Metadata_Encoding struct {
	Encoding string `protobuf:"bytes,800,opt,name=encoding,proto3,oneof"`
}

func (*Metadata_Encoding) isMetadata_EncodingOptional() {}

func (m *Metadata) GetEncodingOptional() isMetadata_EncodingOptional {
	if m != nil {
		return m.EncodingOptional
	}
	return nil
}

func (m *Metadata) GetEncoding() string {
	if x, ok := m.GetEncodingOptional().(*Metadata_Encoding); ok {
		return x.Encoding
	}
	return ""
}

type isMetadata_CompressionOptional interface {
	isMetadata_CompressionOptional()
}

type Metadata_Compression struct {
	Compression string `protobuf:"bytes,900,opt,name=compression,proto3,oneof"`
}

func (*Metadata_Compression) isMetadata_CompressionOptional() {}

func (m *Metadata) GetCompressionOptional() isMetadata_CompressionOptional {
	if m != nil {
		return m.CompressionOptional
	}
	return nil
}

func (m *Metadata) GetCompression() string {
	if x, ok := m.GetCompressionOptional().(*Metadata_Compression); ok {
		return x.Compression
	}
	return ""
}

type isMetadata_FilenameOptional interface {
	isMetadata_FilenameOptional()
}

type Metadata_Filename struct {
	Filename string `protobuf:"bytes,1000,opt,name=filename,proto3,oneof"`
}

func (*Metadata_Filename) isMetadata_FilenameOptional() {}

func (m *Metadata) GetFilenameOptional() isMetadata_FilenameOptional {
	if m != nil {
		return m.FilenameOptional
	}
	return nil
}

func (m *Metadata) GetFilename() string {
	if x, ok := m.GetFilenameOptional().(*Metadata_Filename); ok {
		return x.Filename
	}
	return ""
}

type isMetadata_UrlOptional interface {
	isMetadata_UrlOptional()
}

type Metadata_Url struct {
	Url string `protobuf:"bytes,1100,opt,name=url,proto3,oneof"`
}

func (*Metadata_Url) isMetadata_UrlOptional() {}

func (m *Metadata) GetUrlOptional() isMetadata_UrlOptional {
	if m != nil {
		return m.UrlOptional
	}
	return nil
}

func (m *Metadata) GetUrl() string {
	if x, ok := m.GetUrlOptional().(*Metadata_Url); ok {
		return x.Url
	}
	return ""
}

type isMetadata_S3AddressOptional interface {
	isMetadata_S3AddressOptional()
}

type Metadata_S3Address struct {
	S3Address *S3Address `protobuf:"bytes,1200,opt,name=s3address,proto3,oneof"`
}

func (*Metadata_S3Address) isMetadata_S3AddressOptional() {}

func (m *Metadata) GetS3AddressOptional() isMetadata_S3AddressOptional {
	if m != nil {
		return m.S3AddressOptional
	}
	return nil
}

func (m *Metadata) GetS3Address() *S3Address {
	if x, ok := m.GetS3AddressOptional().(*Metadata_S3Address); ok {
		return x.S3Address
	}
	return nil
}

type isMetadata_DomainOptional interface {
	isMetadata_DomainOptional()
}

type Metadata_Domain struct {
	Domain *Domain `protobuf:"bytes,1300,opt,name=domain,proto3,oneof"`
}

func (*Metadata_Domain) isMetadata_DomainOptional() {}

func (m *Metadata) GetDomainOptional() isMetadata_DomainOptional {
	if m != nil {
		return m.DomainOptional
	}
	return nil
}

func (m *Metadata) GetDomain() *Domain {
	if x, ok := m.GetDomainOptional().(*Metadata_Domain); ok {
		return x.Domain
	}
	return nil
}

type isMetadata_DigestOptional interface {
	isMetadata_DigestOptional()
}

type Metadata_Digest struct {
	Digest *Digest `protobuf:"bytes,1400,opt,name=digest,proto3,oneof"`
}

func (*Metadata_Digest) isMetadata_DigestOptional() {}

func (m *Metadata) GetDigestOptional() isMetadata_DigestOptional {
	if m != nil {
		return m.DigestOptional
	}
	return nil
}

func (m *Metadata) GetDigest() *Digest {
	if x, ok := m.GetDigestOptional().(*Metadata_Digest); ok {
		return x.Digest
	}
	return nil
}

type isMetadata_DescriptionOptional interface {
	isMetadata_DescriptionOptional()
}

type Metadata_Description struct {
	Description string `protobuf:"bytes,1500,opt,name=description,proto3,oneof"`
}

func (*Metadata_Description) isMetadata_DescriptionOptional() {}

func (m *Metadata) GetDescriptionOptional() isMetadata_DescriptionOptional {
	if m != nil {
		return m.DescriptionOptional
	}
	return nil
}

func (m *Metadata) GetDescription() string {
	if x, ok := m.GetDescriptionOptional().(*Metadata_Description); ok {
		return x.Description
	}
	return ""
}

type isMetadata_LenOptional interface {
	isMetadata_LenOptional()
}

type Metadata_Len struct {
	Len int64 `protobuf:"varint,1600,opt,name=len,proto3,oneof"`
}

func (*Metadata_Len) isMetadata_LenOptional() {}

func (m *Metadata) GetLenOptional() isMetadata_LenOptional {
	if m != nil {
		return m.LenOptional
	}
	return nil
}

func (m *Metadata) GetLen() int64 {
	if x, ok := m.GetLenOptional().(*Metadata_Len); ok {
		return x.Len
	}
	return 0
}

type isMetadata_OffsetOptional interface {
	isMetadata_OffsetOptional()
}

type Metadata_Offset struct {
	Offset int64 `protobuf:"varint,1700,opt,name=offset,proto3,oneof"`
}

func (*Metadata_Offset) isMetadata_OffsetOptional() {}

func (m *Metadata) GetOffsetOptional() isMetadata_OffsetOptional {
	if m != nil {
		return m.OffsetOptional
	}
	return nil
}

func (m *Metadata) GetOffset() int64 {
	if x, ok := m.GetOffsetOptional().(*Metadata_Offset); ok {
		return x.Offset
	}
	return 0
}

type isMetadata_LastOptional interface {
	isMetadata_LastOptional()
}

type Metadata_Last struct {
	Last bool `protobuf:"varint,1800,opt,name=last,proto3,oneof"`
}

func (*Metadata_Last) isMetadata_LastOptional() {}

func (m *Metadata) GetLastOptional() isMetadata_LastOptional {
	if m != nil {
		return m.LastOptional
	}
	return nil
}

func (m *Metadata) GetLast() bool {
	if x, ok := m.GetLastOptional().(*Metadata_Last); ok {
		return x.Last
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Metadata) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Metadata_Type)(nil),
		(*Metadata_Name)(nil),
		(*Metadata_Version)(nil),
		(*Metadata_UserId)(nil),
		(*Metadata_Id)(nil),
		(*Metadata_ReferenceId)(nil),
		(*Metadata_Ts)(nil),
		(*Metadata_Encoding)(nil),
		(*Metadata_Compression)(nil),
		(*Metadata_Filename)(nil),
		(*Metadata_Url)(nil),
		(*Metadata_S3Address)(nil),
		(*Metadata_Domain)(nil),
		(*Metadata_Digest)(nil),
		(*Metadata_Description)(nil),
		(*Metadata_Len)(nil),
		(*Metadata_Offset)(nil),
		(*Metadata_Last)(nil),
	}
}

func init() {
	proto.RegisterEnum("atlas.MetadataType", MetadataType_name, MetadataType_value)
	proto.RegisterType((*Metadata)(nil), "atlas.Metadata")
}

func init() { proto.RegisterFile("type_metadata.proto", fileDescriptor_6b5234c8ffbbe006) }

var fileDescriptor_6b5234c8ffbbe006 = []byte{
	// 608 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x93, 0x3b, 0x8e, 0x13, 0x4d,
	0x10, 0xc7, 0x77, 0xfc, 0x76, 0x8d, 0xbd, 0xb6, 0x7b, 0x77, 0xbf, 0xaf, 0x31, 0x02, 0x2c, 0x10,
	0xd2, 0x80, 0xc4, 0xac, 0x16, 0x9f, 0xc0, 0xc8, 0x96, 0xc6, 0xc1, 0x26, 0xbd, 0x5e, 0x52, 0x6b,
	0xd6, 0xdd, 0xb6, 0x46, 0x9a, 0x87, 0x35, 0xdd, 0x46, 0x22, 0x27, 0x20, 0x24, 0xe0, 0x00, 0x04,
	0x84, 0x04, 0x1c, 0x80, 0x80, 0x90, 0x00, 0x11, 0x13, 0x70, 0x00, 0x0e, 0x40, 0x40, 0x88, 0xba,
	0xe6, 0x0d, 0x61, 0xfd, 0xea, 0xdf, 0x8f, 0xfa, 0x57, 0x15, 0x9c, 0xa8, 0x97, 0x7b, 0xb1, 0x0e,
	0x84, 0x72, 0xb9, 0xab, 0x5c, 0x7b, 0x1f, 0x47, 0x2a, 0x22, 0x4d, 0x57, 0xf9, 0xae, 0x1c, 0xdf,
	0xdb, 0x45, 0xd1, 0xce, 0x17, 0xe7, 0x08, 0x6f, 0x0e, 0xdb, 0x73, 0xe5, 0x05, 0x42, 0x2a, 0x37,
	0xd8, 0x27, 0xba, 0xf1, 0x00, 0x0f, 0x1f, 0x0e, 0x1e, 0x4f, 0x01, 0x49, 0x80, 0x14, 0xf1, 0x3a,
	0x67, 0x67, 0xc8, 0xe4, 0x74, 0xed, 0x72, 0x1e, 0x0b, 0x29, 0x53, 0x3c, 0x42, 0xcc, 0xa3, 0xc0,
	0xf5, 0xc2, 0x2a, 0xf2, 0x76, 0x42, 0xaa, 0x04, 0xdd, 0xff, 0xd6, 0x86, 0xce, 0x65, 0xfa, 0x39,
	0x72, 0x0a, 0x0d, 0xad, 0xa0, 0x7c, 0x62, 0x58, 0x4d, 0xe7, 0x88, 0x61, 0x44, 0xce, 0xa0, 0x11,
	0xba, 0x81, 0xa0, 0x5f, 0x8c, 0x89, 0x61, 0x75, 0x1d, 0x83, 0x61, 0x48, 0x6e, 0x43, 0xfb, 0x85,
	0x88, 0xa5, 0x17, 0x85, 0xf4, 0x43, 0x0d, 0x0f, 0xd4, 0x58, 0x46, 0xc8, 0x23, 0x68, 0xa7, 0x9f,
	0xa4, 0x6f, 0xea, 0x13, 0xc3, 0x32, 0x9f, 0xf6, 0x6d, 0xac, 0xd9, 0xbe, 0x96, 0x22, 0x5e, 0xce,
	0x9d, 0x3a, 0x6b, 0x69, 0xc1, 0x92, 0x93, 0xbb, 0x50, 0xf3, 0x38, 0xfd, 0x95, 0xa8, 0xcc, 0x4c,
	0x75, 0xbd, 0x9c, 0x3b, 0x0d, 0x56, 0xf3, 0x38, 0xb9, 0x80, 0x5e, 0x2c, 0xb6, 0x22, 0x16, 0xe1,
	0x46, 0xe8, 0xfb, 0xbe, 0x37, 0xfe, 0x55, 0x36, 0x99, 0x99, 0x6b, 0x96, 0x9c, 0x3c, 0x81, 0x9a,
	0x92, 0xf4, 0x53, 0x13, 0x85, 0x63, 0x3b, 0x71, 0xd9, 0xce, 0x5c, 0xb6, 0x57, 0x99, 0xcb, 0x4e,
	0x8b, 0xd5, 0x94, 0x24, 0x77, 0xa0, 0x23, 0xc2, 0x4d, 0xc4, 0xbd, 0x70, 0x47, 0xdf, 0xb5, 0xb0,
	0xc8, 0x36, 0xcb, 0x11, 0x79, 0x00, 0xe6, 0x26, 0x0a, 0xf6, 0xda, 0x5a, 0x5d, 0xec, 0xab, 0x36,
	0x2a, 0x3a, 0xac, 0x4c, 0xf5, 0x1d, 0x5b, 0xcf, 0x17, 0x68, 0xd4, 0xcf, 0x44, 0xd1, 0x65, 0x39,
	0x22, 0x27, 0x50, 0x3f, 0xc4, 0x3e, 0xfd, 0xda, 0xc1, 0x0c, 0x30, 0x1d, 0x91, 0x0b, 0xe8, 0xca,
	0x69, 0xda, 0x34, 0xfa, 0xb1, 0x8b, 0xbf, 0x1d, 0xa6, 0x65, 0x5d, 0x4d, 0x67, 0x49, 0xc2, 0x31,
	0x59, 0xa1, 0x22, 0x16, 0xb4, 0x92, 0x8e, 0xd2, 0xb7, 0x50, 0xb1, 0x75, 0x8e, 0xd4, 0xe9, 0xb1,
	0x34, 0x8f, 0x4a, 0x6c, 0x34, 0xfd, 0xfd, 0x97, 0x12, 0xa9, 0xd3, 0x67, 0x69, 0x5e, 0xd7, 0xc7,
	0x85, 0xdc, 0xc4, 0xde, 0x5e, 0xe9, 0xfa, 0x7e, 0x98, 0xf8, 0xc7, 0x63, 0x56, 0xa6, 0xba, 0x00,
	0x5f, 0x84, 0xf4, 0x73, 0x6f, 0x62, 0x58, 0x75, 0x67, 0xc0, 0x74, 0x44, 0x6e, 0x41, 0x2b, 0xda,
	0x6e, 0xa5, 0x50, 0xf4, 0x7d, 0x1f, 0xf9, 0x90, 0xa5, 0x40, 0x0f, 0x8d, 0xef, 0x4a, 0x45, 0x5f,
	0x1f, 0x4f, 0x0c, 0xab, 0xe3, 0x8c, 0x18, 0x86, 0xcf, 0x06, 0xd0, 0xc7, 0x19, 0x8c, 0xf0, 0x56,
	0xd7, 0xd7, 0x40, 0x1b, 0x54, 0x00, 0x02, 0xc3, 0x74, 0x88, 0x2a, 0x2c, 0x9d, 0xa6, 0x82, 0xf5,
	0xc1, 0x2c, 0x87, 0xff, 0xc3, 0x59, 0x79, 0x4a, 0x8a, 0xc4, 0x29, 0x90, 0x7c, 0xab, 0x0a, 0x7a,
	0x02, 0xa3, 0xac, 0xbf, 0x05, 0xfc, 0x0f, 0x4e, 0x4b, 0x2d, 0xad, 0x88, 0xb3, 0x46, 0x16, 0xf0,
	0x18, 0x7a, 0x87, 0xd8, 0xaf, 0xbc, 0x93, 0xb7, 0xa9, 0xa0, 0x23, 0x18, 0x24, 0xfd, 0xa8, 0x22,
	0x34, 0xbe, 0xf2, 0x70, 0xc9, 0xeb, 0xca, 0x1b, 0xbe, 0xa8, 0x1e, 0x4d, 0xec, 0xad, 0xf8, 0xa7,
	0x8d, 0xcd, 0xc1, 0xe3, 0x87, 0xd0, 0xcb, 0xf6, 0x79, 0x95, 0x6c, 0xef, 0xe8, 0x72, 0xb1, 0x9a,
	0xcd, 0x67, 0xab, 0xd9, 0x9a, 0x2d, 0xae, 0x16, 0xec, 0xf9, 0x62, 0x3e, 0x3c, 0xba, 0x69, 0xe1,
	0x36, 0x4c, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xba, 0xf0, 0xe0, 0x7f, 0x9f, 0x04, 0x00, 0x00,
}
