// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type_data_chunk.proto

package mservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataChunkType int32

const (
	// Due to first enum value has to be zero in proto3
	DataChunkType_DATA_CHUNK_TYPE_RESERVED    DataChunkType = 0
	DataChunkType_DATA_CHUNK_TYPE_UNSPECIFIED DataChunkType = 100
	DataChunkType_DATA_CHUNK_TYPE_DATA        DataChunkType = 200
)

var DataChunkType_name = map[int32]string{
	0:   "DATA_CHUNK_TYPE_RESERVED",
	100: "DATA_CHUNK_TYPE_UNSPECIFIED",
	200: "DATA_CHUNK_TYPE_DATA",
}

var DataChunkType_value = map[string]int32{
	"DATA_CHUNK_TYPE_RESERVED":    0,
	"DATA_CHUNK_TYPE_UNSPECIFIED": 100,
	"DATA_CHUNK_TYPE_DATA":        200,
}

func (x DataChunkType) String() string {
	return proto.EnumName(DataChunkType_name, int32(x))
}

func (DataChunkType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c69e33da091858ca, []int{0}
}

// DataChunk is a chunk of data transferred as a single piece.
// Can be part of bigger data, transferred by chunks
type DataChunk struct {
	Header *Header `protobuf:"bytes,100,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to MetadataOptional:
	//	*DataChunk_Metadata
	MetadataOptional isDataChunk_MetadataOptional `protobuf_oneof:"metadata_optional"`
	// Types that are valid to be assigned to LenOptional:
	//	*DataChunk_Len
	LenOptional isDataChunk_LenOptional `protobuf_oneof:"len_optional"`
	// Types that are valid to be assigned to OffsetOptional:
	//	*DataChunk_Offset
	OffsetOptional isDataChunk_OffsetOptional `protobuf_oneof:"offset_optional"`
	// Types that are valid to be assigned to LastOptional:
	//	*DataChunk_Last
	LastOptional isDataChunk_LastOptional `protobuf_oneof:"last_optional"`
	// Bytes is the purpose of the whole data chunk type
	// May contain any arbitrary sequence of bytes no longer than 2^32
	Bytes                []byte   `protobuf:"bytes,600,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataChunk) Reset()         { *m = DataChunk{} }
func (m *DataChunk) String() string { return proto.CompactTextString(m) }
func (*DataChunk) ProtoMessage()    {}
func (*DataChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69e33da091858ca, []int{0}
}

func (m *DataChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataChunk.Unmarshal(m, b)
}
func (m *DataChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataChunk.Marshal(b, m, deterministic)
}
func (m *DataChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataChunk.Merge(m, src)
}
func (m *DataChunk) XXX_Size() int {
	return xxx_messageInfo_DataChunk.Size(m)
}
func (m *DataChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_DataChunk.DiscardUnknown(m)
}

var xxx_messageInfo_DataChunk proto.InternalMessageInfo

func (m *DataChunk) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

type isDataChunk_MetadataOptional interface {
	isDataChunk_MetadataOptional()
}

type DataChunk_Metadata struct {
	Metadata *Metadata `protobuf:"bytes,200,opt,name=metadata,proto3,oneof"`
}

func (*DataChunk_Metadata) isDataChunk_MetadataOptional() {}

func (m *DataChunk) GetMetadataOptional() isDataChunk_MetadataOptional {
	if m != nil {
		return m.MetadataOptional
	}
	return nil
}

func (m *DataChunk) GetMetadata() *Metadata {
	if x, ok := m.GetMetadataOptional().(*DataChunk_Metadata); ok {
		return x.Metadata
	}
	return nil
}

type isDataChunk_LenOptional interface {
	isDataChunk_LenOptional()
}

type DataChunk_Len struct {
	Len int64 `protobuf:"varint,300,opt,name=len,proto3,oneof"`
}

func (*DataChunk_Len) isDataChunk_LenOptional() {}

func (m *DataChunk) GetLenOptional() isDataChunk_LenOptional {
	if m != nil {
		return m.LenOptional
	}
	return nil
}

func (m *DataChunk) GetLen() int64 {
	if x, ok := m.GetLenOptional().(*DataChunk_Len); ok {
		return x.Len
	}
	return 0
}

type isDataChunk_OffsetOptional interface {
	isDataChunk_OffsetOptional()
}

type DataChunk_Offset struct {
	Offset int64 `protobuf:"varint,400,opt,name=offset,proto3,oneof"`
}

func (*DataChunk_Offset) isDataChunk_OffsetOptional() {}

func (m *DataChunk) GetOffsetOptional() isDataChunk_OffsetOptional {
	if m != nil {
		return m.OffsetOptional
	}
	return nil
}

func (m *DataChunk) GetOffset() int64 {
	if x, ok := m.GetOffsetOptional().(*DataChunk_Offset); ok {
		return x.Offset
	}
	return 0
}

type isDataChunk_LastOptional interface {
	isDataChunk_LastOptional()
}

type DataChunk_Last struct {
	Last bool `protobuf:"varint,500,opt,name=last,proto3,oneof"`
}

func (*DataChunk_Last) isDataChunk_LastOptional() {}

func (m *DataChunk) GetLastOptional() isDataChunk_LastOptional {
	if m != nil {
		return m.LastOptional
	}
	return nil
}

func (m *DataChunk) GetLast() bool {
	if x, ok := m.GetLastOptional().(*DataChunk_Last); ok {
		return x.Last
	}
	return false
}

func (m *DataChunk) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DataChunk) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DataChunk_Metadata)(nil),
		(*DataChunk_Len)(nil),
		(*DataChunk_Offset)(nil),
		(*DataChunk_Last)(nil),
	}
}

func init() {
	proto.RegisterEnum("mservice.DataChunkType", DataChunkType_name, DataChunkType_value)
	proto.RegisterType((*DataChunk)(nil), "mservice.DataChunk")
}

func init() {
	proto.RegisterFile("type_data_chunk.proto", fileDescriptor_c69e33da091858ca)
}

var fileDescriptor_c69e33da091858ca = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xd1, 0x6a, 0xf2, 0x30,
	0x18, 0x86, 0x8d, 0xf5, 0x17, 0xff, 0x6f, 0x3a, 0x6b, 0x9c, 0x10, 0xdd, 0x60, 0xb2, 0xa3, 0xb2,
	0x03, 0x61, 0xdb, 0x15, 0xa8, 0xcd, 0xa8, 0x8c, 0x89, 0x44, 0x1d, 0xec, 0x28, 0x44, 0x1b, 0x51,
	0x56, 0xdb, 0x62, 0xb3, 0x81, 0x57, 0xb1, 0x5d, 0xc8, 0x2e, 0xc4, 0x4b, 0xd8, 0x85, 0xec, 0x02,
	0x46, 0x52, 0xb5, 0xe0, 0xe1, 0xfb, 0xbc, 0xef, 0xf7, 0x14, 0x1a, 0x68, 0xa8, 0x6d, 0x2c, 0xb9,
	0x2f, 0x94, 0xe0, 0xf3, 0xe5, 0x7b, 0xf8, 0xd6, 0x89, 0x37, 0x91, 0x8a, 0x70, 0x69, 0x9d, 0xc8,
	0xcd, 0xc7, 0x6a, 0x2e, 0x5b, 0x35, 0x33, 0x58, 0x4a, 0xe1, 0xcb, 0x4d, 0x5a, 0xb6, 0xea, 0x06,
	0xad, 0xa5, 0x12, 0xfa, 0x2e, 0x85, 0x37, 0x9f, 0x79, 0xf8, 0xef, 0x0a, 0x25, 0xfa, 0xda, 0x82,
	0x1d, 0x28, 0xa6, 0x27, 0xc4, 0x6f, 0x23, 0xe7, 0xec, 0xde, 0xee, 0x1c, 0x84, 0x1d, 0xcf, 0x70,
	0xb6, 0xef, 0xf1, 0x1d, 0x94, 0x0e, 0x26, 0xb2, 0x43, 0x66, 0x8c, 0xb3, 0xf1, 0xf3, 0xbe, 0xf2,
	0x72, 0xec, 0x38, 0xc3, 0x75, 0xb0, 0x02, 0x19, 0x92, 0xef, 0x7c, 0x1b, 0x39, 0x96, 0x87, 0x98,
	0x4e, 0xb8, 0x09, 0xc5, 0x68, 0xb1, 0x48, 0xa4, 0x22, 0x5f, 0x96, 0xe1, 0x79, 0xb6, 0x07, 0xb8,
	0x01, 0x85, 0x40, 0x24, 0x8a, 0xfc, 0xea, 0xa2, 0xe4, 0x59, 0xcc, 0x44, 0xdc, 0x80, 0x7f, 0xb3,
	0xad, 0x92, 0x09, 0xf9, 0x29, 0xb4, 0x91, 0x53, 0x66, 0x69, 0xea, 0xd5, 0xa1, 0x76, 0xf8, 0x12,
	0x8f, 0x62, 0xb5, 0x8a, 0x42, 0x11, 0xf4, 0xce, 0xa1, 0x1c, 0xc8, 0x30, 0xcb, 0x35, 0xa8, 0xa6,
	0xf2, 0x0c, 0x55, 0xa1, 0xa2, 0xb5, 0x47, 0x70, 0xbb, 0x82, 0xca, 0xf1, 0x87, 0x4c, 0xb6, 0xb1,
	0xc4, 0x57, 0x40, 0xdc, 0xee, 0xa4, 0xcb, 0xfb, 0xde, 0x74, 0xf8, 0xc4, 0x27, 0xaf, 0x23, 0xca,
	0x19, 0x1d, 0x53, 0xf6, 0x42, 0x5d, 0x3b, 0x87, 0xaf, 0xe1, 0xf2, 0xb4, 0x9d, 0x0e, 0xc7, 0x23,
	0xda, 0x1f, 0x3c, 0x0e, 0xa8, 0x6b, 0xfb, 0xb8, 0x09, 0x17, 0xa7, 0x03, 0x9d, 0xed, 0x1d, 0x9a,
	0x15, 0xcd, 0x1b, 0x3c, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xd7, 0x02, 0x41, 0xce, 0x01,
	0x00, 0x00,
}
