{
 "title": "Atlas",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All API endpoint calls count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "atlas",
     "dateTimeColDataType": "d",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\n  AND action_id=1\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(d), 1) * 1) * 1000 as t,     count() FROM atlas.api_journal WHERE d BETWEEN toDateTime(1596813154) AND toDateTime(1596813274)   AND action_id=1 GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "api_journal"
    }
   ]
  },
  {
   "title": "All API endpoint errors count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "atlas",
     "dateTimeColDataType": "d",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  count()\nFROM $table\nWHERE $timeFilter\n  AND action_id=7\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT     (intDiv(toUInt32(d), 30) * 30) * 1000 as t,     count() FROM atlas.api_journal WHERE d BETWEEN toDateTime(1596632323) AND toDateTime(1596665550)   AND action_id=1 GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "api_journal"
    }
   ]
  },
  {
   "title": "DataChunks endpoint calls count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "atlas",
     "dateTimeColDataType": "d",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  count()\nFROM $table\nWHERE $timeFilter\n  AND endpoint_id=1\n  AND action_id=1\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT   (intDiv(toUInt32(d), 1) * 1) * 1000 as t,   count() FROM atlas.api_journal WHERE d BETWEEN toDateTime(1596918300) AND toDateTime(1596918607)   AND endpoint_id=1   AND action_id=1 GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "api_journal"
    }
   ]
  },
  {
   "title": "DataChunks endpoint errors count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "atlas",
     "dateTimeColDataType": "d",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  count()\nFROM $table\nWHERE $timeFilter\n  AND endpoint_id=1\n  AND action_id=7\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT   (intDiv(toUInt32(d), 1) * 1) * 1000 as t,   count() FROM atlas.api_journal WHERE d BETWEEN toDateTime(1596918300) AND toDateTime(1596918607)   AND endpoint_id=1   AND action_id=7 GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "api_journal"
    }
   ]
  },
  {
   "title": "All API endpoint MAX duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "atlas",
     "dateTimeColDataType": "d",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  MAX(duration)\nFROM $table\nWHERE $timeFilter\nGROUP BY t, call_id\nORDER BY t\n",
     "rawQuery": "SELECT   (intDiv(toUInt32(d), 1) * 1) * 1000 as t,   MAX(duration) FROM atlas.api_journal WHERE d BETWEEN toDateTime(1596918300) AND toDateTime(1596918607) GROUP BY t, call_id ORDER BY t",
     "round": "0s",
     "table": "api_journal"
    }
   ]
  },
  {
   "title": "DataChunks endpoint MAX duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "atlas",
     "dateTimeColDataType": "d",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  MAX(duration)\nFROM $table\nWHERE $timeFilter\n  AND endpoint_id=1\nGROUP BY t, call_id\nORDER BY t\n",
     "rawQuery": "SELECT   (intDiv(toUInt32(d), 1) * 1) * 1000 as t,   MAX(duration) FROM atlas.api_journal WHERE d BETWEEN toDateTime(1596918300) AND toDateTime(1596918607)   AND endpoint_id=1 GROUP BY t, call_id ORDER BY t",
     "round": "0s",
     "table": "api_journal"
    }
   ]
  },
  {
   "title": "Reports endpoint MAX duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "atlas",
     "dateTimeColDataType": "d",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  $timeSeries as t,\n  MAX(duration)\nFROM $table\nWHERE $timeFilter\n  AND endpoint_id=2\nGROUP BY t, call_id\nORDER BY t\n",
     "rawQuery": "SELECT   (intDiv(toUInt32(d), 20) * 20) * 1000 as t,   MAX(duration) FROM atlas.api_journal WHERE d >= toDateTime(1596897944)   AND endpoint_id=2 GROUP BY t, call_id ORDER BY t",
     "round": "0s",
     "table": "api_journal"
    }
   ]
  }
 ]
}